bugfix: 主机Agent状态同步性能优化 #1403
TencentBlueKing/bk-job pull request #1818
Opened 2023-03-08 07:33 UTC by liuliaozhong

2023-03-10 06:37 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/ApplicationHostDAO.java
> +    List<ApplicationHostDTO> listHostSimpleInfo(long bizId);
建议不要复用ApplicationHostDTO这个DTO，新建一个，避免误用到未赋值字段导致空指针异常

2023-03-10 06:41 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/ApplicationHostDAO.java
> +    int batchUpdateHostStatusByHostId(DSLContext dslContext, List<ApplicationHostDTO> hostInfoList);
去除dslContext参数，使用DAO内置的，如果没有内置的则添加一个，一开始使用这个参数是出于事务考虑，后续都改用声明式事务

2023-03-10 06:41 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/ApplicationHostDAO.java
> +    int updateHostStatusByHostId(DSLContext dslContext, ApplicationHostDTO hostInfoDTO);
去除dslContext参数

2023-03-10 06:52 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/impl/ApplicationHostDAOImpl.java
> +        TABLE.CLOUD_IP
APP_ID、IP、CLOUD_AREA_ID这3个字段都是多余的

2023-03-10 06:58 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/impl/ApplicationHostDAOImpl.java
> +            .orderBy(TABLE.IS_AGENT_ALIVE.desc(), TABLE.HOST_ID.asc());
无须排序，损耗性能

2023-03-10 07:41 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/impl/ApplicationHostDAOImpl.java
> +    public int batchUpdateHostStatusByHostId(DSLContext dslContext, List<ApplicationHostDTO> hostInfoList) {
方法名称与方法参数含义不太一致，建议将hostIdList与status作为参数

2023-03-10 08:40 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/impl/ApplicationHostDAOImpl.java
> +                    Collectors.mapping(ApplicationHostDTO::getHostId, Collectors.toList())));
分组聚合的逻辑建议放到上层，不放DAO层

2023-03-10 08:41 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/impl/ApplicationHostDAOImpl.java
> +        if(hostInfoDTO!=null && hostInfoDTO.getHostId()!=0){
判断逻辑错误

2023-03-10 08:53 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/impl/ApplicationHostDAOImpl.java
> +    public int updateHostStatusByHostId(DSLContext dslContext, ApplicationHostDTO hostInfoDTO) {
建议简化参数为hostId和agentAlive，方法名称也考虑改一下

2023-03-10 08:58 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/HostServiceImpl.java
> +            // 批量更新失败，尝试逐条更新
新的方案里面，不需要这个逻辑了，做好分批次更新后，失败了打印异常信息即可

2023-03-10 12:09 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/ApplicationHostDAO.java
> +    int batchUpdateHostStatusByHostId(DSLContext dslContext, List<ApplicationHostDTO> hostInfoList);
已去除dslContext

2023-03-10 12:10 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/ApplicationHostDAO.java
> +    List<ApplicationHostDTO> listHostSimpleInfo(long bizId);
确实容易混，已新建DTO

2023-03-10 12:10 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/impl/ApplicationHostDAOImpl.java
> +        TABLE.CLOUD_IP
已去除

2023-03-10 12:11 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/impl/ApplicationHostDAOImpl.java
> +                    Collectors.mapping(ApplicationHostDTO::getHostId, Collectors.toList())));
放在上层service了

2023-03-10 12:11 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/HostServiceImpl.java
> +            // 批量更新失败，尝试逐条更新
去掉了

2023-03-10 12:15 UTC, jsonwan requested changes
一些问题需要处理下

2023-03-13 09:54 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/sync/AgentStatusSyncService.java
> +        List<ApplicationHostDTO> localBizAppHosts = applicationHostDAO.listHostSimpleInfo(bizId);
已改

2023-03-13 09:55 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/impl/ApplicationHostDAOImpl.java
> +        TABLE.CLOUD_IP
APP_ID没去除，在后续更新缓存需要用到

2023-03-13 09:56 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/impl/ApplicationHostDAOImpl.java
> +        TABLE.CLOUD_IP
APP_ID没去除，在后续更新缓存需要用到这字段

2023-03-14 12:36 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/HostServiceImpl.java
> +                    hostCache.addOrUpdateHost(applicationHostDTO);
是否会导致未赋值的字段覆盖旧缓存中已赋值字段？

2023-03-14 12:47 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/sync/AgentStatusSyncService.java
> +        List<ApplicationHostSimpleDTO> localBizAppHosts = applicationHostDAO.listAllHostSimpleInfo();
命名需要相应调整

2023-03-14 12:47 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/sync/AgentStatusSyncService.java
> +        log.debug("Performance:syncAppHostAgentStatus:{}", appHostAgentStatusWatch);
超过3min用INFO打出来

2023-03-14 12:49 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/sync/AgentStatusSyncService.java
> +            log.error("syncAgentStatus of app fail：", t);
日志内容需要相应调整

2023-03-14 12:51 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/sync/AgentStatusSyncService.java
>          log.info(Thread.currentThread().getName() + ":Finished:sync agentStatus from GSE," +
去除外层业务循环后，这一句可以挪到try内容的末尾

2023-03-14 12:52 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/HostService.java
> +    int updateHostsStatusInBiz(List<ApplicationHostSimpleDTO> simpleHostList);
方法名称不正确，这里的主机不一定是同一业务下了

2023-03-14 12:53 UTC, jsonwan commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/model/dto/ApplicationHostSimpleDTO.java
> +public class ApplicationHostSimpleDTO {
去掉Application更简洁，直接对应host表

2023-03-14 12:56 UTC, jsonwan commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/model/dto/ApplicationHostSimpleDTO.java
> +    private Boolean gseAgentAlive;
这里的类型与host字段类型对齐，应该是个Integer，如果处理过程中需要转成布尔值，在上层代码去转

2023-03-14 12:57 UTC, jsonwan requested changes
一些小问题需要处理下

2023-03-15 13:50 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/HostServiceImpl.java
> +                    hostCache.addOrUpdateHost(applicationHostDTO);
有点，确实存在这样的坑，改成显示赋值了

2023-03-15 13:51 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/HostServiceImpl.java
> +        log.debug("Performance:updateHostsStatus:{}", watch);
已添加

2023-03-16 12:08 UTC, jsonwan approved these changes

2023-03-16 12:09 UTC, jsonwan commented
联合开发环境验证无误后合入

2023-03-16 12:58 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/HostServiceImpl.java
>                      end = start + batchSize;
batchSize调整为5000，减小更新时对其他写入语句的阻塞时间。

2023-03-16 13:00 UTC, jsonwan commented
外层调用逻辑可以优化，去除线程池，单个线程即可，减小CPU和内存占用。

2023-03-16 13:44 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/sync/AgentStatusSyncService.java
> +        hostService.updateHostsStatus(localHosts);
日志增加了总记录数，成功修改的记录数

2023-03-16 13:48 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/sync/SyncServiceImpl.java
> -            syncAgentStatusExecutor.execute(() -> {
线程池不再被使用之后，它的初始化和度量的代码也要相应去掉，否则还是会被创建出来，核心线程还是会闲置

2023-03-16 13:50 UTC, jsonwan requested changes
1个问题需要处理

2023-03-16 14:16 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/sync/SyncServiceImpl.java
> -            syncAgentStatusExecutor.execute(() -> {
把相关的代码删除了

2023-03-17 02:26 UTC, jsonwan approved these changes

2023-03-17 02:26 UTC, merged