perf: 主机Agent状态同步性能优化 #1403
TencentBlueKing/bk-job pull request #1862
Opened 2023-03-21 02:25 UTC by liuliaozhong

2023-03-21 04:01 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/sync/AgentStatusSyncService.java
> +        hostAgentStatusWatch.start("getAgentStatusByAppInfo from GSE");
ByAppInfo可以去掉

2023-03-21 04:03 UTC, jsonwan requested changes
1个小问题需要处理

2023-03-21 05:54 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/sync/AgentStatusSyncService.java
> +        hostAgentStatusWatch.start("getAgentStatusByAppInfo from GSE");
已去掉了

2023-03-22 02:13 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/HostService.java
> +    List<HostSimpleDTO>  listNeedChangedHostCompareToGSE(List<HostSimpleDTO> hosts);
方法名改为findStatusChangedHosts

2023-03-22 02:14 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/HostServiceImpl.java
> +        List<HostSimpleDTO> needChangedHosts = new ArrayList<>();
变量名改为statusChangedHosts，意义指向更明确

2023-03-22 02:17 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/sync/AgentStatusSyncService.java
> +        List<HostSimpleDTO> needChangedHosts = hostService.listNeedChangedHostCompareToGSE(localHosts);
变量名改为statusChangedHosts，意义指向更明确

2023-03-22 02:17 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/sync/AgentStatusSyncService.java
> +        log.debug("syncHostAgentStatus Performance,totalHosts:{};needChangedHosts:{};succHosts:{};timeConsume:{}",
变量名调整，另外，日志级别改为INFO，希望在正常日志中看到有多少主机状态被更新了

2023-03-22 02:18 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/sync/AgentStatusSyncService.java
> +            log.info("syncHostAgentStatus too slow, run statistics,totalHosts:{};needChangedHosts:{};succHosts:{};" +
日志级别改为WARN

2023-03-22 02:18 UTC, jsonwan requested changes
几个小问题需要处理下

2023-03-22 04:04 UTC, jsonwan approved these changes

2023-03-22 04:05 UTC, merged