perf: 提供根据GSE Task ID自助查询任务链接的Web接口 #1843
TencentBlueKing/bk-job pull request #1945
Opened 2023-04-12 03:54 UTC by liuliaozhong

2023-04-14 07:20 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebSearchToolsResourceImpl.java
> +        AuthResult authResult = appAuthService.auth(username, ActionId.ACCESS_BUSINESS, appResourceScope);
鉴权逻辑错误，这个请求不是在具体的业务下发起的，JobContextUtil拿到的appResourceScope应该是null，要鉴权的业务是gseTaskId对应的任务所在的业务

2023-04-14 07:24 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebSearchToolsResourceImpl.java
> +        StepInstanceBaseDTO stepInstanceBase = stepInstanceService.getStepInstanceBase(gseTaskDTO.getStepInstanceId());
要注意区分脚本步骤与文件步骤，空字段拼接出来的链接可能不正确

2023-04-14 07:25 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/dao/impl/GseTaskDAOImpl.java
> +        Record record  = dslContext.select(ALL_FIELDS).from(TABLE)
只查需要的字段，不要查所有的

2023-04-14 07:26 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/dao/impl/GseTaskDAOImpl.java
> +            .where(TABLE.GSE_TASK_ID.eq(gseTaskId))
检查gseTaskId字段上是否有索引，没有的话需要添加，这张表数据量可能非常大

2023-04-14 07:28 UTC, jsonwan requested changes
几个问题需要处理。

2023-04-16 04:47 UTC, liuliaozhong commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/dao/impl/GseTaskDAOImpl.java
> +            .where(TABLE.GSE_TASK_ID.eq(gseTaskId))
gseTaskId字段有索引

2023-04-16 04:52 UTC, liuliaozhong commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebSearchToolsResourceImpl.java
> +        StepInstanceBaseDTO stepInstanceBase = stepInstanceService.getStepInstanceBase(gseTaskDTO.getStepInstanceId());
脚本步骤和文件步骤对应的stepInstance对象哪个字段可能会为空呢

2023-04-17 03:34 UTC, jsonwan reviewed
请部署至开发环境验收

2023-04-17 11:51 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebSearchToolsResourceImpl.java
> +        StepInstanceBaseDTO stepInstanceBase = stepInstanceService.getStepInstanceBase(gseTaskDTO.getStepInstanceId());
非滚动执行的任务batch可能为空，不过默认值是0

2023-04-17 13:16 UTC, jsonwan approved these changes

2023-04-18 02:23 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebSearchToolsResourceImpl.java
> +        StepInstanceBaseDTO stepInstanceBase = stepInstanceService.getStepInstanceBase(stepInstanceId);
鉴权部分重复，可以进一步抽象

2023-04-18 02:24 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebSearchToolsResourceImpl.java
> +                if (gseTaskDTO != null) gseTaskDTOList.add(gseTaskDTO);
把大括号加上，if语句的括号不要省略，容易造成歧义

2023-04-18 02:24 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebSearchToolsResourceImpl.java
> +            if (gseTaskDTO != null) gseTaskDTOList.add(gseTaskDTO);
把大括号加上，if语句的括号不要省略，容易造成歧义

2023-04-18 02:25 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebSearchToolsResourceImpl.java
> +            GseTaskDTO gseTaskDTO = gseTaskService.getGseTask(stepInstanceId, 0, 0);
两个0都提取成常量，避免魔法值

2023-04-18 02:28 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebSearchToolsResourceImpl.java
> +                                          int executeCount, int batch, String gseTaskId) {
一个参数一行，有利于减少不同参数修改合并带来的代码冲突

2023-04-18 02:28 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebSearchToolsResourceImpl.java
> +            taskLinkVOList.add(convertToTaskLinVO(resourceScope, stepInstanceBase, gseTaskDTO.getExecuteCount(),
一个参数一行，有利于减少不同参数修改合并带来的代码冲突

2023-04-18 02:29 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebSearchToolsResourceImpl.java
> +        TaskLinkVO taskLinkVO = convertToTaskLinVO(resourceScope, stepInstanceBase, stepInstanceBase.getExecuteCount(),
一个参数一行，有利于减少不同参数修改合并带来的代码冲突

2023-04-18 02:29 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebSearchToolsResourceImpl.java
> +                    stepInstanceRollingTaskDTO.getExecuteCount(), stepInstanceRollingTaskDTO.getBatch());
一个参数一行，有利于减少不同参数修改合并带来的代码冲突

2023-04-18 02:30 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebSearchToolsResourceImpl.java
> +                    taskLinkVO.getStepInstanceId(), taskLinkVO.getExecuteCount(), taskLinkVO.getBatch()));
一个参数一行，有利于减少不同参数修改合并带来的代码冲突

2023-04-18 02:31 UTC, jsonwan requested changes
几个小问题需要处理

2023-04-18 07:28 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebSearchToolsResourceImpl.java
> +        AuthResult authResult = auth(username, appResourceScope);
前后还是有重复的代码

2023-04-19 11:31 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/web/impl/WebSearchToolsResourceImpl.java
> +            return Response.buildCommonFailResp(ErrorCode.ILLEGAL_PARAM);
这里最好用一个带原因的错误码，把参数错误的原因抛出去

2023-04-19 14:35 UTC, jsonwan requested changes
2个小问题

2023-04-20 07:39 UTC, jsonwan approved these changes

2023-04-21 04:01 UTC, merged