fix: IP选择器对搜索后进行全选时，错误将全部数据给全选了 #2076
TencentBlueKing/bk-job pull request #2079
Opened 2023-05-23 14:32 UTC by jsonwan

2023-05-24 02:28 UTC, wangyu096 requested changes

2023-05-24 02:28 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/impl/ApplicationHostDAOImpl.java
> +        if (CollectionUtils.isNotEmpty(ipKeys)) {
1. 这个方法的行数有点长了
2. 这个构造or条件的Condition看过去似乎有通用的逻辑，能否使用一个方法抽象下？

2023-05-25 01:45 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/impl/ApplicationHostDAOImpl.java
> +        if (CollectionUtils.isNotEmpty(ipKeys)) {
已修改

2023-05-25 01:50 UTC, wangyu096 approved these changes

2023-05-25 01:50 UTC, merged