feat: 脚本执行敏感参数存储支持国密 #2055
TencentBlueKing/bk-job pull request #2096
Opened 2023-05-30 13:13 UTC by jsonwan

1. 基于SDK封装对称加密服务；
2. 支持默认+具体场景两种粒度指定加密算法；
3. 支持通过ServiceLoader的方式自行拓展加解密方法；
4. 支持加密算法切换。

2023-06-01 02:43 UTC, irwinsun approved these changes

2023-07-28 02:19 UTC, wangyu096 requested changes

2023-07-28 02:19 UTC, wangyu096 commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/exception/CryptoException.java
> +
这个类是否可以放到 common-crypto 模块中？

2023-07-28 02:19 UTC, wangyu096 commented on src/backend/commons/common-utils/src/main/java/com/tencent/bk/job/common/util/crypto/AESUtils.java
> +    public static void encrypt(InputStream in, OutputStream out, String password) throws Exception {
定义了 CryptoException, 这里可以考虑抛出 CryptoException 这种运行时异常。ASEUtils,RSAUtils 其他方法类似

2023-07-28 07:33 UTC, jsonwan commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/exception/CryptoException.java
> +
已改为使用SDK中的CryptoException类。

2023-07-28 07:33 UTC, jsonwan commented on src/backend/commons/common-utils/src/main/java/com/tencent/bk/job/common/util/crypto/AESUtils.java
> +    public static void encrypt(InputStream in, OutputStream out, String password) throws Exception {
已修改

2023-08-01 02:04 UTC, merged