perf: 优化作业模板、执行方案资源的创建、更新的Web请求校验日志 #2101
TencentBlueKing/bk-job pull request #2102
Opened 2023-06-01 07:34 UTC by wangyu096

1. JobContextUtil.addDebugMessage("") 方式修改为log.warn("")，解决异常抛出时没有错误日志漏打印的问题
2. 校验失败抛出InvalidParamException，更加简洁
3. 优化校验代码

2023-06-01 09:54 UTC, jsonwan commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/web/vo/task/TaskStepVO.java
> +            throw new InvalidParamException(ErrorCode.ILLEGAL_PARAM);
不符合原有逻辑

2023-06-01 10:03 UTC, jsonwan commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/web/vo/task/TaskStepVO.java
> +                scriptStepInfo.validate(isCreate);
可能空指针异常

2023-06-01 10:03 UTC, jsonwan commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/web/vo/task/TaskStepVO.java
> +                fileStepInfo.validate(isCreate);
可能空指针异常

2023-06-01 10:03 UTC, jsonwan commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/web/vo/task/TaskStepVO.java
> +                approvalStepInfo.validate(isCreate);
可能空指针异常

2023-06-01 10:04 UTC, jsonwan commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/web/vo/task/TaskStepVO.java
> +                log.warn("Invalid step type");
建议把type打出来，便于排查

2023-06-01 10:05 UTC, jsonwan commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/web/vo/task/TaskVariableVO.java
> +            log.warn("Invalid variable type!");
建议把type和正确的取值范围打出来，便于排查

2023-06-01 10:06 UTC, jsonwan commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/web/vo/task/TaskVariableVO.java
> +            log.warn("Invalid require option!");
建议把required和正确的取值范围打出来，便于排查

2023-06-01 10:18 UTC, jsonwan requested changes
几个小问题需要处理

2023-06-02 01:36 UTC, wangyu096 commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/web/vo/task/TaskStepVO.java
> +            throw new InvalidParamException(ErrorCode.ILLEGAL_PARAM);
fixed

2023-06-02 01:44 UTC, wangyu096 commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/web/vo/task/TaskStepVO.java
> +                scriptStepInfo.validate(isCreate);
fixed

2023-06-02 01:44 UTC, wangyu096 commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/web/vo/task/TaskStepVO.java
> +                scriptStepInfo.validate(isCreate);
fixed

2023-06-02 01:44 UTC, wangyu096 commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/web/vo/task/TaskStepVO.java
> +                fileStepInfo.validate(isCreate);
fixed

2023-06-02 01:44 UTC, wangyu096 commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/web/vo/task/TaskStepVO.java
> +                approvalStepInfo.validate(isCreate);
fixed

2023-06-02 01:45 UTC, wangyu096 commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/web/vo/task/TaskStepVO.java
> +                log.warn("Invalid step type");
fixed

2023-06-02 01:45 UTC, wangyu096 commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/web/vo/task/TaskVariableVO.java
> +            log.warn("Invalid variable type!");
fixed

2023-06-02 01:46 UTC, wangyu096 commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/web/vo/task/TaskVariableVO.java
> +            log.warn("Invalid require option!");
fixed

2023-06-02 01:59 UTC, merged