fix: 文件源文件下载进度日志丢失 #2283
TencentBlueKing/bk-job pull request #2284
Opened 2023-07-27 09:51 UTC by jsonwan

指定RedisTemplate Key类型为String

2023-07-27 09:55 UTC, wangyu096 requested changes

2023-07-27 09:55 UTC, wangyu096 commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/service/impl/FileSourceTaskServiceImpl.java
> +                                     RedisTemplate<String, Object> redisTemplate,
使用 Qulifier 指定为 jsonRedisTemplate

2023-07-27 09:55 UTC, wangyu096 commented on src/backend/job-file-gateway/api-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/model/resp/inner/ThirdFileSourceTaskLogDTO.java
> +public class ThirdFileSourceTaskLogDTO implements Serializable {
类中需要包含序列化的 ID 字段

2023-07-27 10:19 UTC, jsonwan commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/service/impl/FileSourceTaskServiceImpl.java
> +                                     RedisTemplate<String, Object> redisTemplate,
已修改

2023-07-27 10:19 UTC, jsonwan commented on src/backend/job-file-gateway/api-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/model/resp/inner/ThirdFileSourceTaskLogDTO.java
> +public class ThirdFileSourceTaskLogDTO implements Serializable {
已修改

2023-07-28 02:04 UTC, wangyu096 commented
RedisTemplateConfig.java 应该用不上的，为了避免后面出现引用错误，建议删除掉

2023-07-28 02:06 UTC, jsonwan commented
> RedisTemplateConfig.java 应该用不上的，为了避免后面出现引用错误，建议删除掉

是RestTemplate，不存在RedisTemplateConfig

2023-07-28 02:07 UTC, wangyu096 commented
> > RedisTemplateConfig.java 应该用不上的，为了避免后面出现引用错误，建议删除掉
> 
> 是RestTemplate，不存在RedisTemplateConfig

ok

2023-07-31 02:22 UTC, merged