feat: 脚本开放管理类API #2318
TencentBlueKing/bk-job pull request #2345
Opened 2023-08-18 07:11 UTC by liuliaozhong

2023-08-28 09:00 UTC, wangyu096 commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/esb/v3/response/EsbManageScriptV3DTO.java
> +public class EsbManageScriptV3DTO {
可删除，复用 EsbScriptDTO

2023-08-28 09:01 UTC, wangyu096 commented
另外需要注意下，部分 API 返回的脚本实例中不应该包含 content 等敏感信息（需要检查）

2023-08-28 09:27 UTC, liuliaozhong commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages.properties
> +validation.constraints.NotBlankField.message=不能为空
拼接了具体字段，比如fieldName="content"，用户看到的是‘content不能为空‘，这样是否可行呢？还是content也要相应的国际化，

2023-08-28 13:06 UTC, wangyu096 requested changes

2023-08-28 13:06 UTC, wangyu096 commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/esb/v3/request/EsbCreatePublicScriptV3Req.java
> +    @NotContainSpecialChar(fieldName = "name", groups = Create.class)
这个报错有问题，用户可能无法理解 name

2023-08-28 13:06 UTC, wangyu096 commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/esb/v3/request/EsbUpdatePublicScriptBasicV3Req.java
> +    @NotContainSpecialChar(fieldName = "name", groups = Update.class)
涉及 @NotContainSpecialChar 的地方的使用，由于报错提示不人性化，可能需要修改

2023-08-28 13:06 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/esb/impl/v3/EsbScriptResourceV3Impl.java
> +        if (scriptService.isScriptReferenced(scriptId, null)) {
这个可以在 deleteScript中调用，属于删除的公共逻辑

2023-08-28 13:06 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/esb/impl/v3/EsbScriptResourceV3Impl.java
> +        if (scriptService.isScriptReferenced(scriptId, versionId)) {
这个可以在 ScriptService.deleteScript 中判断

2023-08-29 05:41 UTC, liuliaozhong commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/esb/v3/response/EsbCreatePublicScriptV3DTO.java
> +public class EsbCreatePublicScriptV3DTO {
已删除

2023-08-29 05:41 UTC, liuliaozhong commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages_en.properties
> +validation.constraints.ScriptVersion_notNull.message=Script version not null
已修改

2023-08-29 05:44 UTC, liuliaozhong commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/esb/v3/request/EsbCreatePublicScriptV3Req.java
> +    @NotContainSpecialChar(fieldName = "name", groups = Create.class)
已改成@Pattern注解，报错返回具体message

2023-08-29 05:46 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/esb/impl/v3/EsbScriptResourceV3Impl.java
> +        if (scriptService.isScriptReferenced(scriptId, null)) {
已移到deleteScript()、deleteScriptVersion()中

2023-08-29 08:24 UTC, liuliaozhong commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/api/esb/v3/EsbPublicScriptV3Resource.java
> +    EsbResp<EsbCreatePublicScriptV3DTO> createPublicScript(
已修改，拓展了EsbScriptVersionDetailV3DTO，创建、修改、发布、禁用都通过它返回

2023-08-29 08:24 UTC, liuliaozhong commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/api/esb/v3/EsbScriptV3Resource.java
> +    EsbResp<EsbCreateScriptV3DTO> createScript(
已修改，拓展了EsbScriptVersionDetailV3DTO，创建、修改、发布、禁用都通过它返回

2023-08-29 08:26 UTC, liuliaozhong commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/esb/v3/request/EsbCreatePublicScriptV3Req.java
> +    @NotBlankField(fieldName = "content", groups = Create.class)
{filedName}不支持国际化，已改成@notempty注解，有具体的message

2023-08-29 08:27 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/model/dto/ScriptDTO.java
> +    public EsbCreateScriptV3DTO toEsbCreateScriptV3DTO() {
已删除

2023-08-29 08:27 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/model/dto/ScriptDTO.java
> +    public EsbCreatePublicScriptV3DTO toEsbCreatePublicScriptV3DTO() {
已删除

2023-08-29 08:30 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/esb/impl/v3/EsbScriptResourceV3Impl.java
> +        if (checkScriptReferenced(scriptId, null)) {
已改，检查逻辑checkScriptReferenced()放在service中, 在deleteScript(),deleteScriptVersion()分别调用

2023-08-29 08:30 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/esb/impl/v3/EsbScriptResourceV3Impl.java
> +        if (checkScriptReferenced(scriptId, versionId)) {
已改，检查逻辑checkScriptReferenced()放在service中, 在deleteScript(),deleteScriptVersion()分别调用

2023-08-29 08:31 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/esb/impl/v3/EsbScriptResourceV3Impl.java
> +        EsbManageScriptV3DTO esbManageScriptV3DTO = new EsbManageScriptV3DTO(scriptVersionId, scriptId,
已修改，拓展了EsbScriptVersionDetailV3DTO，创建、修改、发布、禁用都通过它返回

2023-08-29 08:31 UTC, liuliaozhong commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/esb/v3/response/EsbManageScriptV3DTO.java
> +public class EsbManageScriptV3DTO {
已修改，拓展了EsbScriptVersionDetailV3DTO，创建、修改、发布、禁用都通过它返回

2023-08-29 08:31 UTC, liuliaozhong commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/esb/v3/response/EsbCreateScriptV3DTO.java
> +public class EsbCreateScriptV3DTO extends EsbAppScopeDTO {
已修改，拓展了EsbScriptVersionDetailV3DTO，创建、修改、发布、禁用都通过它返回

2023-08-29 08:34 UTC, liuliaozhong commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages_en.properties
> +validation.constraints.ScriptName_notNull.message=Script name not null
已修改，validation.constraints.ScriptId_notNull.message=Script id not null 改成了validation.constraints.ScriptId_empty.message=Script id cannot be empty，剩下的几个类似

2023-08-29 08:34 UTC, liuliaozhong commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages_en.properties
> +validation.constraints.ScriptId_notNull.message=Script id not null
已修改

2023-08-29 08:34 UTC, liuliaozhong commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages_en.properties
> +validation.constraints.ScriptContent_notNull.message=Script content not null
已修改

2023-08-29 08:34 UTC, liuliaozhong commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/esb/v3/request/EsbUpdatePublicScriptBasicV3Req.java
> +    @NotContainSpecialChar(fieldName = "name", groups = Update.class)
已改成@pattern注解，报错返回具体message

2023-08-29 08:35 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/esb/impl/v3/EsbScriptResourceV3Impl.java
> +        if (scriptService.isScriptReferenced(scriptId, versionId)) {
已移到service的deleteScript()、deleteScriptVersion()方法中

2023-08-29 09:08 UTC, wangyu096 requested changes

2023-08-29 09:08 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/esb/impl/v3/EsbPublicScriptResourceV3Impl.java
> +        long versionId = request.getScriptVersionId();
建议使用 spring 校验

2023-08-29 09:08 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/esb/impl/v3/EsbScriptResourceV3Impl.java
> +        script.setPublicScript(appResourceScope == null);
这里的都是业务脚本，无需进一步判断，直接设置为 false 即可

2023-08-29 09:08 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptServiceImpl.java
> +            throw new InternalException(ErrorCode.DELETE_REF_SCRIPT_FAIL);
业务逻辑错误，使用 FailedPreconditionException

2023-08-29 09:31 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/ScriptServiceImpl.java
> +            throw new InternalException(ErrorCode.DELETE_REF_SCRIPT_FAIL);
已修改

2023-08-29 09:38 UTC, liuliaozhong commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/esb/v3/request/EsbCreatePublicScriptVersionV3Req.java
> +    @NotEmpty(message = "{validation.constraints.ScriptName_empty.message}", groups = Create.class)
写错了，已修改

2023-08-29 09:44 UTC, liuliaozhong commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/model/esb/v3/response/EsbScriptVersionDetailV3DTO.java
> +@JsonInclude(JsonInclude.Include.NON_NULL)
去掉了，同时我在API文档中说明下，历史原因有的属性返回null也符合预期

2023-08-29 10:02 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/esb/impl/v3/EsbPublicScriptResourceV3Impl.java
> +        long versionId = request.getScriptVersionId();
当时想删除脚本、删除脚本版本都用同一个req，所以放在代码中检验。已去掉，新加了sriptVersionReq，用的@NotEmpty校验

2023-09-06 03:54 UTC, wangyu096 approved these changes

2023-09-06 03:54 UTC, merged