perf: Job支持轻量化部署 #1894
TencentBlueKing/bk-job pull request #2375
Opened 2023-08-24 07:35 UTC by wangyu096

## 目标
1. Job 支持微服务/二进制下的标准（微服务）和轻量化（单体应用）部署，并支持通过运维脚本进行切换不同的部署模式
2. 减少部署资源占用，轻量化部署的场景下，仅需要 1G 内存即可（job-gateway+job-assemble 两个微服务）

## 部署调整

部署方案见 #2279

## 修改内容
1. 新增微服务 job-assemble，作为所有其他微服务（除了 job-config/job-gateway)的启动入口
2. 本地/远程 API 调用方案：自定义SmartFeignClient，基于 spring contional 初始化 FeignClient(如果classpath 中发现 api interface的 RestController 实现，本地调用 API， 不会初始化 FeignClient;否则，初始化FeignClient，远程调用其他微服务)。FeignClient 使用方式也发生变更，不再使用之前的继承 interface 的方式
3. 重构 commons 下的所有模块，支持 springboot starter 方式；合并部分多余的模块（比如 common-cmdb-sdk/common-statistics)
4. 优化配置命名，所有微服务自身的配置增加 job.{module}前缀，解决配置冲突的问题。比如 job.backup
5. 优化 jooq model 生成的 package（默认为 org.jooq.xxx)，解决不同微服务之间生成的*Record.class冲突的问题（修改完之后为 com.tencent.bk.job.{module}.xxxRecord.java)
6. 优化部分API url，解决微服务合并之后资源 URL 冲突的问题
7. 优化Bean name 生成，解决微服务合并之后冲突的问题（UniqueBeanNameGenerator.java)
8. WebInterceptorRegisterAutoConfiguration 实现拦截器的自动注册，避免多个微服务重复配置的问题
9. 缩小微服务 @ComponentScan 扫描范围，不再扫描 commons。解决@Configuration 优先加载导致的 AutoConfiguration 的 @AutoConfigurationBefore/@AutoConfigurationBefore 失效的问题
10. 与运维约定新增 deploy.yml, 部署时候根据该文件部署二进制环境
11. 编译优化：gradle 并行编译；新增模块定义文件（pageage_modules.yml)解决按需编译的问题
12. 新增 api-common-job-{module}, 解决微服务之间共享数据模型的问题（之前定义在 commons-common 模块，这个底层模块权责太多，导致微服务之间依赖关系复杂且不稳定，会发生循环依赖的问题）

2023-08-25 02:10 UTC, irwinsun approved these changes
单体部署验证要点： 要求在多实例DB下部署单体来验证确保JOOQ的改动是有效的。

2023-08-25 04:19 UTC, wangyu096 commented
> 单体部署验证要点： 要求在多实例DB下部署单体来验证确保JOOQ的改动是有效的。

已在多实例 DB 下验证 ok

2023-08-29 02:41 UTC, jsonwan requested changes
存在一些问题需要处理下。

2023-08-29 02:41 UTC, jsonwan commented on src/backend/upgrader/src/main/java/com/tencent/bk/job/upgrader/task/AddHostIdMigrationTask.java
> +                "/migration/manage/action/addHostIdMigrationTask"),
建议manage放在migration前面

2023-08-29 02:41 UTC, jsonwan commented on src/backend/upgrader/src/main/java/com/tencent/bk/job/upgrader/task/AddHostIdMigrationTask.java
> +                "/migration/crontab/action/addHostIdMigrationTask"),
建议crontab放在migration前面，其余地方类似

2023-08-29 02:41 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/VALUES_LOG.md
> +      backup:
这里应该是delete吧

2023-08-29 02:41 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/VALUES_LOG.md
> +  ## 数据归档配置
缺少归档库配置

2023-08-29 02:41 UTC, jsonwan commented on support-files/templates/#etc#job#job-backup#job-backup.yml
> +        backup:
delete配置好像少了

2023-08-29 02:41 UTC, jsonwan commented on support-files/templates/#job#deploy.yml
> +      - job-backup
缺少job-file-gateway与job-file-worker相关配置

2023-08-29 02:41 UTC, jsonwan commented on support-files/templates/#job#deploy_lite.yml
> +      - job-backup
缺少job-file-gateway与job-file-worker相关配置

2023-08-29 02:41 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/values.yaml
> +      backup:
删除配置缺失

2023-08-29 02:56 UTC, wangyu096 commented on src/backend/commons/common-redis/src/main/java/com/tencent/bk/job/common/redis/util/RedisSlideWindowFlowController.java
> +//                log.warn("DANGER:slideWindow update time consuming:" + duration + "ms");
本地调试输出大量的错误日志，临时关闭。已恢复

2023-08-29 02:56 UTC, wangyu096 commented on src/backend/commons/common-redis/src/main/java/com/tencent/bk/job/common/redis/util/RedisSlideWindowFlowController.java
> +//            log.error("Exception when clear slideWindows", e);
本地调试输出大量的错误日志，临时关闭。已恢复

2023-08-29 02:58 UTC, wangyu096 commented on src/backend/job-analysis/api-common-job-analysis/build.gradle
> +//    implementation("org.apache.commons:commons-collections4")
已删除

2023-08-29 02:59 UTC, wangyu096 commented on src/backend/job-backup/service-job-backup/src/main/java/com/tencent/bk/job/backup/archive/JobExecuteArchiveManage.java
> +                    archiveDBProperties,
fixed

2023-08-29 03:00 UTC, wangyu096 commented on src/backend/job-backup/service-job-backup/src/main/java/com/tencent/bk/job/backup/archive/impl/GseFileAgentTaskArchivist.java
> +                archiveDBProperties,
已全量修改

2023-08-29 03:03 UTC, wangyu096 commented on src/backend/upgrader/src/main/java/com/tencent/bk/job/upgrader/client/JobClient.java
> +    private static final String URL_SET_BIZ_SET_MIGRATION_STATUS = "/migration/manage/action/setBizSetMigrationStatus";
已修改其他类似的路径，统一把模块加在最前面

2023-08-29 03:03 UTC, wangyu096 commented on src/backend/upgrader/src/main/java/com/tencent/bk/job/upgrader/task/AddHostIdMigrationTask.java
> +                "/migration/manage/action/addHostIdMigrationTask"),
fixed

2023-08-29 03:03 UTC, wangyu096 commented on src/backend/upgrader/src/main/java/com/tencent/bk/job/upgrader/task/AddHostIdMigrationTask.java
> +                "/migration/crontab/action/addHostIdMigrationTask"),
fixed

2023-08-29 03:05 UTC, wangyu096 commented on support-files/kubernetes/charts/bk-job/VALUES_LOG.md
> +  ## 数据归档配置
已补充

2023-08-29 03:14 UTC, wangyu096 commented on support-files/templates/#etc#job#job-backup#job-backup.yml
> +        backup:
```yaml
backupConfig:
  ## 数据归档配置
  archive:
    # job-execute模块的归档配置
    execute:
      # 是否启用 DB 归档
      enabled: false
      # 归档任务运行的cron表达式，默认每天凌晨04:00
      cron: 0 0 4 * * *
      # 热库中的数据保留时间（天）
      keep_days: 30
      backup:
        # 是否启用 DB 数据备份
        enabled: false
```

新版本配置有更改。因为之前的归档配置有点儿奇怪。“归档”这个词本身就包含了从旧表中删除原始数据的含义。之前的版本用 archive.enabled=false&archive.delete.enabled=true 表示删除原始表的数据有点奇怪。

新版本使用 archive.execute.enabled=true 开启归档，会删除原表数据；使用 archive.execute.backup.enable=true 表示需要备份原来的数据。更加合理一些

2023-08-29 03:27 UTC, wangyu096 commented on support-files/templates/#job#deploy_lite.yml
> +      - job-backup
这个文件主要用与通过运维的部署方案部署社区版/企业版。由于当前文件源相关的服务并没有开放给外部的二进制版本，所以这里为了保持一致不需要配置

2023-08-29 03:27 UTC, wangyu096 commented on support-files/templates/#job#deploy.yml
> +      - job-backup
这个文件主要用与通过运维的部署方案部署社区版/企业版。由于当前文件源相关的服务并没有开放给外部的二进制版本，所以这里为了保持一致不需要配置

2023-08-29 03:30 UTC, wangyu096 commented on support-files/kubernetes/charts/bk-job/values.yaml
> +      backup:
```yaml
backupConfig:
  ## 数据归档配置
  archive:
    # job-execute模块的归档配置
    execute:
      # 是否启用 DB 归档
      enabled: false
      # 归档任务运行的cron表达式，默认每天凌晨04:00
      cron: 0 0 4 * * *
      # 热库中的数据保留时间（天）
      keep_days: 30
      backup:
        # 是否启用 DB 数据备份
        enabled: false
```

新版本配置有更改。因为之前的归档配置有点儿奇怪。“归档”这个词本身就包含了从旧表中删除原始数据的含义。之前的版本用 archive.enabled=false&archive.delete.enabled=true 表示删除原始表的数据有点奇怪。

新版本使用 archive.execute.enabled=true 开启归档，会删除原表数据；使用 archive.execute.backup.enable=true 表示需要备份原来的数据。更加合理一些

2023-08-29 03:33 UTC, wangyu096 commented on src/backend/commons/common-web/src/main/java/com/tencent/bk/job/common/web/config/WebInterceptorAutoRegister.java
> +        });
这里的考虑主要是后续要支持多个微服务之间的组合部署，不同的组合方式 Interceptor 没办法预定义。为了解决 Order 的顺序问题，通过 Interceptor order 预定义了拦截器的顺序。基本上拦截器都是按照这个逻辑的
```
/**
 * Job 拦截器 ORDER 定义
 */
public interface InterceptorOrder {

    /**
     * 对请求进行预处理（检查、限流、记录、修改请求等）
     */
    interface Init {
        int HIGHEST = 1;
        int LOWEST = 100;
        /**
         * 检查请求合法性
         */
        int CHECK_VALID = HIGHEST;
        /**
         * 日志记录
         */
        int LOG = HIGHEST + 1;
        /**
         * 请求统计
         */
        int METRICS = HIGHEST + 2;
        /**
         * 请求处理
         */
        int REWRITE_REQUEST = HIGHEST + 2;
    }

    /**
     * 用户认证
     */
    interface Identification {
        int HIGHEST = 101;
        int LOWEST = 200;
    }

    /**
     * 用户鉴权
     */
    interface AUTH {
        int HIGHEST = 201;
        int LOWEST = 300;
        /**
         * 全局鉴权
         */
        int AUTH_GLOBAL = HIGHEST;
        /**
         * 普通鉴权
         */
        int AUTH_COMMON = HIGHEST + 50;
    }

    /**
     * 业务逻辑
     */
    interface Business {
        int HIGHEST = 301;
        int LOWEST = 400;
    }

    /**
     * 请求处理完成
     */
    interface Completion {
        int HIGHEST = 401;
        int LOWEST = 500;
    }
}
```

2023-08-29 04:07 UTC, jsonwan commented on support-files/templates/#etc#job#job-backup#job-backup.yml
> +        backup:
但是如何表达“仅删除”这个意思呢？用delete更清晰地告诉用户做了什么，把“归档”理解为包含删除还是有一定理解成本的

2023-08-29 04:07 UTC, jsonwan commented on support-files/templates/#job#deploy_lite.yml
> +      - job-backup
ok

2023-08-29 04:07 UTC, jsonwan commented on support-files/templates/#job#deploy.yml
> +      - job-backup
ok

2023-08-29 04:07 UTC, jsonwan commented on src/backend/commons/common-redis/src/main/java/com/tencent/bk/job/common/redis/util/RedisSlideWindowFlowController.java
> +//                log.warn("DANGER:slideWindow update time consuming:" + duration + "ms");
ok

2023-08-29 04:08 UTC, jsonwan commented on src/backend/commons/common-redis/src/main/java/com/tencent/bk/job/common/redis/util/RedisSlideWindowFlowController.java
> +//            log.error("Exception when clear slideWindows", e);
ok

2023-08-29 04:10 UTC, jsonwan commented on src/backend/commons/common-web/src/main/java/com/tencent/bk/job/common/web/config/WebInterceptorAutoRegister.java
> +        });
ok

2023-08-29 04:12 UTC, jsonwan commented
归档部分的配置需要再斟酌下

2023-08-30 04:29 UTC, wangyu096 commented on support-files/templates/#etc#job#job-backup#job-backup.yml
> +        backup:
使用新的配置：
```yaml
backupConfig:
  ## 数据归档配置
  archive:
    # 归档使用的MariaDB实例，若开启归档且开启 DB 数据备份，必须配置该项内容
    mariadb:
      host: ""
      port: ""
      username: "job"
      password: "job"
      connection:
        properties: ?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    # job-execute模块的归档配置
    execute:
      # 是否启用 DB 归档
      enabled: false
      # 归档模式。deleteOnly: 仅删除； backupThenDelete: 先备份数据再删除。默认 deleteOnly
      mode: deleteOnly
      # 归档任务运行的cron表达式，默认每天凌晨04:00
      cron: 0 0 4 * * *
      # 热库中的数据保留时间（天）
      keep_days: 30
```

2023-08-31 02:12 UTC, jsonwan commented
![image](https://github.com/TencentBlueKing/bk-job/assets/53823124/06e75492-8c9c-4d4e-8a11-1e4033b49eea)
有2个地方有deleteDirect需要核实下

2023-08-31 02:25 UTC, wangyu096 commented
> ![image](https://user-images.githubusercontent.com/53823124/264514820-06e75492-8c9c-4d4e-8a11-1e4033b49eea.png) 有2个地方有deleteDirect需要核实下

已修改

2023-08-31 02:31 UTC, jsonwan approved these changes

2023-08-31 02:31 UTC, merged