fix: 粘贴从其他业务复制的标签，导致公共脚本列表页面报错 #2183
TencentBlueKing/bk-job pull request #2427
Opened 2023-09-05 09:33 UTC by liuliaozhong

2023-10-13 04:21 UTC, wangyu096 requested changes

2023-10-13 04:21 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/TagServiceImpl.java
> -        tags.forEach(tag -> {
1. 看了下 checkTags的调用，都是在请求资源列表的时候给资源设置标签用的。这里可以不用 check
2. 从设置资源标签那里保证标签的合法性（比如，给脚本加标签，保证加入的标签必须是当前业务下的标签）

2024-02-20 02:40 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/TagServiceImpl.java
> -        tags.forEach(tag -> {
在设置标签的时候已添加合法性校验，标签不合法则设置失败。请求列表时要是去掉check的话，如果底量数据已有标签脏数据的话，列表会显示标签脏数据，这样不太符合预期吧？checkTags逻辑可以保留着，check到标签脏数据不要报错remove掉，保证列表页面的正常显示

2024-02-20 02:54 UTC, wangyu096 requested changes

2024-02-20 02:54 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/TagServiceImpl.java
> -        tags.forEach(tag -> {
ok

2024-02-20 02:54 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/TagServiceImpl.java
> +                log.warn(String.format("Tag is not exist, appId=%s, tagId=%s", appId, tag.getId()));
日志优化：
log.info("Tag is not exist, appId={}, tagId={}", appId, tag.getId());

2024-02-20 03:24 UTC, merged