fix: file-worker任务状态更新请求无序到达导致第三方源文件偶现分发失败 #2434
TencentBlueKing/bk-job pull request #2443
Opened 2023-09-13 03:52 UTC by jsonwan

1. 任务状态更新支持事务与写入锁定，保证多条关联数据更新的原子性；
2. 优化文件下载任务表索引；
3. DAO层代码全部改用声明式事务；
4. 删除部分未使用的冗余代码；
5. 优化file-worker线程池配置，增加监控。

2023-09-13 06:25 UTC, wangyu096 requested changes

2023-09-13 06:25 UTC, wangyu096 commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/service/impl/FileSourceServiceImpl.java
> +                                 FileSourceDAO fileSourceDAO, FileWorkerDAO fileWorkerDAO) {
换行有点奇怪

2023-09-13 06:25 UTC, wangyu096 commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/service/impl/FileSourceTaskServiceImpl.java
> +                                     FileTaskDAO fileTaskDAO, FileWorkerDAO fileworkerDAO,
换行格式

2023-09-13 06:25 UTC, wangyu096 commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/service/impl/FileSourceTaskServiceImpl.java
> +    @Transactional(rollbackFor = {Throwable.class})
@Transactional 需要value 属性指定TransactionManager（轻量化部署不指定的情况下会报错）)

2023-09-13 06:25 UTC, wangyu096 commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/service/impl/FileSourceTaskServiceImpl.java
> +    @Transactional(rollbackFor = {Throwable.class})
@Transactional 需要value 属性指定TransactionManager（轻量化部署不指定的情况下会报错）)

2023-09-13 06:25 UTC, wangyu096 commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/service/listener/impl/FileSourceTaskStatusUpdater.java
> +                                       FileTaskDAO fileTaskDAO, FileSourceTaskStatusChangeListener listener) {
换行格式

2023-09-14 03:02 UTC, jsonwan commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/service/impl/FileSourceServiceImpl.java
> +                                 FileSourceDAO fileSourceDAO, FileWorkerDAO fileWorkerDAO) {
已修改

2023-09-14 03:02 UTC, jsonwan commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/service/impl/FileSourceTaskServiceImpl.java
> +                                     FileTaskDAO fileTaskDAO, FileWorkerDAO fileworkerDAO,
已修改

2023-09-14 03:04 UTC, jsonwan commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/service/listener/impl/FileSourceTaskStatusUpdater.java
> +                                       FileTaskDAO fileTaskDAO, FileSourceTaskStatusChangeListener listener) {
已修改

2023-09-14 03:09 UTC, jsonwan commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/service/impl/FileSourceTaskServiceImpl.java
> +    @Transactional(rollbackFor = {Throwable.class})
已修改

2023-09-14 03:09 UTC, jsonwan commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/service/impl/FileSourceTaskServiceImpl.java
> +    @Transactional(rollbackFor = {Throwable.class})
已修改

2023-09-14 03:24 UTC, wangyu096 approved these changes

2023-09-14 03:25 UTC, merged