feature: Job 对接审计中心 #1765
TencentBlueKing/bk-job pull request #2460
Opened 2023-09-18 04:12 UTC by wangyu096

1. 新增 common-audit 模块
2. 通过注解方式标识审计事件
3. 代码改造：鉴权/审计公共逻辑放到 Service层，避免通过 ESB、WEB 渠道调用重复处理；Service 层提供两种方法，包含 username 参数的用户态方法（会进行鉴权、审计等操作）与内部使用的方法（直接执行业务逻辑，跳过审计、鉴权等前置检查）。
4. 代码改造：Create/Update 资源的方法统一返回变更之后的资源
5. 代码改造：Web API 分离创建/更新操作，不再放在一个 API 实现，避免代码复杂
6. 自定义审计 logger，二进制输出日志到磁盘上的 audit_event.log; 容器化环境输出到容器内部 audit_event.log (已配置logback 自动清理来确保不会占用太多存储)

2023-09-18 13:49 UTC, jsonwan commented on src/backend/commons/common-audit/src/main/java/com/tencent/bk/job/common/audit/config/JobAuditAutoConfiguration.java
> +@ConditionalOnProperty(name = "audit.enabled", havingValue = "true", matchIfMissing = true)
是要默认开启审计吗

2023-09-19 03:48 UTC, jsonwan commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/util/I18nUtil.java
>      private static MessageI18nService i18nService;
需要加volatile

2023-09-19 03:53 UTC, jsonwan commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/util/I18nUtil.java
> +        return getI18nMessage(key, null);
这里直接将locale忽略了，逻辑不太对吧

2023-09-20 01:43 UTC, jsonwan requested changes
几个小问题需要处理下

2023-09-20 02:10 UTC, wangyu096 commented on src/backend/commons/common-audit/src/main/java/com/tencent/bk/job/common/audit/config/JobAuditAutoConfiguration.java
> +@ConditionalOnProperty(name = "audit.enabled", havingValue = "true", matchIfMissing = true)
是的，需要默认打开

2023-09-20 02:11 UTC, wangyu096 commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/util/I18nUtil.java
> +        return getI18nMessage(key, null);
fixed

2023-09-20 02:15 UTC, wangyu096 commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/util/I18nUtil.java
>      private static MessageI18nService i18nService;
fixed

2023-09-20 13:38 UTC, jsonwan approved these changes

2023-09-21 00:52 UTC, merged