fix: Job 二进制版本无损升级失效 #2467
TencentBlueKing/bk-job pull request #2468
Opened 2023-09-21 09:30 UTC by wangyu096

#2467 

## 修改
1. 自动装配 GracefulShutdown 组件

2023-09-21 09:55 UTC, jsonwan approved these changes

2023-09-21 09:55 UTC, jsonwan requested changes
建议提到3.8.x

2023-09-22 01:39 UTC, wangyu096 commented
> 建议提到3.8.x

fixed

2023-09-22 01:39 UTC, jsonwan approved these changes

2023-09-22 04:23 UTC, merged