feat: 【高危语句规则】新增高危语句规则管理功能的API，给上层SaaS使用 #2383
TencentBlueKing/bk-job pull request #2485
Opened 2023-09-26 08:00 UTC by liuliaozhong

2023-09-26 09:37 UTC, wangyu096 requested changes

2023-09-26 09:37 UTC, wangyu096 commented on docs/apidoc/esb/jobv3-confapis/apidocs/zh_hans/check_script.md
> +    "script_language": [1],
一次只检查一种脚本，这里不应该是 array

2023-09-26 09:37 UTC, wangyu096 commented on docs/apidoc/esb/jobv3-confapis/apidocs/zh_hans/check_script.md
> +            "description": "脚本首行没有定义合法的脚本类型，例如： #!/bin/bash"
demo 尽量用英文，方便在中英文文档之间共享

2023-09-26 09:37 UTC, wangyu096 commented on docs/apidoc/esb/jobv3-confapis/apidocs/zh_hans/check_script.md
> +            "action": null,
这里的 action 为啥是 null？

2023-09-26 09:37 UTC, wangyu096 commented on docs/apidoc/esb/jobv3-confapis/apidocs/zh_hans/check_script.md
> +            "action": 2,
脚本检测API 似乎不应该返回 action 字段，因为只是检测，并不会进行拦截等操作

2023-09-26 09:37 UTC, wangyu096 commented on docs/apidoc/esb/jobv3-confapis/apidocs/zh_hans/check_script.md
> +脚本检测。
脚本检测 -> 高危脚本检测

2023-09-26 09:37 UTC, wangyu096 commented on docs/apidoc/esb/jobv3-confapis/apidocs/zh_hans/check_script.md
> +            "code": null,
错误代码并非高危语句检测需要的字段，可以不返回

2023-09-26 09:37 UTC, wangyu096 commented on docs/apidoc/esb/jobv3-confapis/apidocs/zh_hans/update_dangerous_rule.md
> +        "order": 1,
暂时隐藏 order 优先级参数，无需返回

2023-09-26 09:37 UTC, wangyu096 commented on docs/apidoc/esb/jobv3-confapis/job.yaml
> +- path: /v2/jobv3/get_dangerous_rule_list/
待确认。需要咨询下 ESB 是否支持用 GET 传 RequestBody

2023-09-26 10:02 UTC, liuliaozhong commented on docs/apidoc/esb/jobv3-confapis/apidocs/zh_hans/check_script.md
> +    "script_language": [1],
已修改

2023-09-26 10:03 UTC, liuliaozhong commented on docs/apidoc/esb/jobv3-confapis/apidocs/zh_hans/check_script.md
> +            "description": "脚本首行没有定义合法的脚本类型，例如： #!/bin/bash"
已修改

2023-09-26 10:10 UTC, liuliaozhong commented on docs/apidoc/esb/jobv3-confapis/apidocs/zh_hans/check_script.md
> +            "action": null,
内置高危语句检测没有action属性

2023-09-26 10:15 UTC, liuliaozhong commented on docs/apidoc/esb/jobv3-confapis/apidocs/zh_hans/check_script.md
> +            "action": 2,
已改

2023-09-26 11:27 UTC, wangyu096 commented on docs/apidoc/esb/jobv3-confapis/apidocs/zh_hans/check_script.md
> +    "script_language": [1],
ok

2023-09-26 11:27 UTC, wangyu096 commented on docs/apidoc/esb/jobv3-confapis/apidocs/zh_hans/check_script.md
> +            "description": "脚本首行没有定义合法的脚本类型，例如： #!/bin/bash"
ok

2023-09-26 11:28 UTC, wangyu096 commented on docs/apidoc/esb/jobv3-confapis/apidocs/zh_hans/check_script.md
> +            "action": 2,
ok

2023-09-26 11:28 UTC, wangyu096 commented on docs/apidoc/esb/jobv3-confapis/apidocs/zh_hans/check_script.md
> +脚本检测。
ok

2023-10-10 02:22 UTC, wangyu096 requested changes

2023-10-10 02:22 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/esb/impl/v3/EsbDangerousRuleV3ResourceImpl.java
> +        return EsbResp.buildCommonFailResp(ErrorCode.INTERNAL_ERROR);
这里可以重构下，如果删除报错，直接在 Service 里边处理，抛出异常，而不是用 id 来判断结果

2023-10-10 02:22 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/globalsetting/DangerousRuleDAO.java
> +    int updateDangerousRuleStatus(String userName, Long id, Integer status);
status 参数直接使用枚举类型，方法会更加清晰

2023-10-10 08:25 UTC, liuliaozhong commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages.properties
> +validation.constraints.InvalidJobHighRiskGrammarId_empty.message=语法检测ID不能为空
已修改

2023-10-10 08:28 UTC, liuliaozhong commented on docs/apidoc/esb/jobv3-confapis/apidocs/en/check_script.md
> +            "lineContent": "rm /tmp",
dto是下划线格式，文档从别处copy的，没注意，已改

2023-10-10 08:28 UTC, liuliaozhong commented on docs/apidoc/esb/jobv3-confapis/apidocs/en/check_script.md
> +            "matchContent": "rm /tmp",
已改

2023-10-10 08:28 UTC, liuliaozhong commented on docs/apidoc/esb/jobv3-confapis/apidocs/en/check_script.md
> +            "matchContent": "rm",
已改

2023-10-10 08:28 UTC, liuliaozhong commented on docs/apidoc/esb/jobv3-confapis/apidocs/zh_hans/check_script.md
> +            "lineContent": "rm /tmp",
已改

2023-10-10 08:28 UTC, liuliaozhong commented on docs/apidoc/esb/jobv3-confapis/apidocs/zh_hans/check_script.md
> +            "matchContent": "rm /tmp",
已改

2023-10-10 08:28 UTC, liuliaozhong commented on docs/apidoc/esb/jobv3-confapis/apidocs/zh_hans/check_script.md
> +            "matchContent": "rm",
已改

2023-10-10 08:28 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/esb/impl/v3/EsbDangerousRuleV3ResourceImpl.java
> +        return EsbResp.buildCommonFailResp(ErrorCode.INTERNAL_ERROR);
已放在service处理

2023-10-10 08:29 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/dao/globalsetting/DangerousRuleDAO.java
> +    int updateDangerousRuleStatus(String userName, Long id, Integer status);
已改

2023-11-15 08:31 UTC, wangyu096 approved these changes

2023-11-15 08:31 UTC, merged