fix: 创建凭证后缺少编辑与使用权限 #2457
TencentBlueKing/bk-job pull request #2534
Opened 2023-10-20 08:04 UTC by liuliaozhong

2023-10-23 03:24 UTC, jsonwan requested changes
1个问题需要处理。

2023-10-23 03:24 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/web/impl/WebCredentialResourceImpl.java
> +            ticketAuthService.registerTicket(username, id, createUpdateReq.getName());
如果这句抛出异常，将出现凭证创建了、用户无权限、且接口返回失败的情况，调用方重新创建时会报凭据已存在的错误，这里需要用MySQL声明式事务保证下二者的原子性。
另外，创建文件源的接口也帮忙一起改一下，加一下事务保证。

2023-10-23 03:57 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/web/impl/WebCredentialResourceImpl.java
> +            ticketAuthService.registerTicket(username, id, createUpdateReq.getName());
已添加，文件源接口也加了

2023-10-23 04:03 UTC, jsonwan reviewed
代码没问题后，请在新的联合开发环境上提交一个测试用的验证作业

2024-03-14 04:08 UTC, jsonwan commented
请增加版本依赖声明：
权限中心SaaS bk_iam>=V1.10.18

参考信息：
https://github.com/TencentBlueKing/bk-iam-saas/issues/2388

权限中心交包：

【社区版 6.1】
后台：/ce/iam/bkiam_ce-1.12.10.tgz
SaaS: /ce/saas/bk_iam/bk_iam_V1.10.18.tar.gz
bkiam-search-engine: /ee/iam_search_engine/bkiam_search_engine-1.1.2.tgz

【社区版 7.0】
bkiam                      0.2.9
bkiam-saas                 0.2.25
bkiam-search-engine        0.1.2

版本日志：
https://github.com/TencentBlueKing/bk-iam-saas/releases/tag/v1.10.18
https://github.com/TencentBlueKing/bk-iam/releases/tag/v1.12.10
https://github.com/TencentBlueKing/bk-iam-search-engine/releases/tag/v1.1.2

2024-03-14 07:04 UTC, liuliaozhong commented
> 请增加版本依赖声明： 权限中心SaaS bk_iam>=V1.10.18
> 
> 参考信息： [TencentBlueKing/bk-iam-saas#2388](https://github.com/TencentBlueKing/bk-iam-saas/issues/2388)
> 
> 权限中心交包：
> 
> 【社区版 6.1】 后台：/ce/iam/bkiam_ce-1.12.10.tgz SaaS: /ce/saas/bk_iam/bk_iam_V1.10.18.tar.gz bkiam-search-engine: /ee/iam_search_engine/bkiam_search_engine-1.1.2.tgz
> 
> 【社区版 7.0】 bkiam 0.2.9 bkiam-saas 0.2.25 bkiam-search-engine 0.1.2
> 
> 版本日志： https://github.com/TencentBlueKing/bk-iam-saas/releases/tag/v1.10.18 https://github.com/TencentBlueKing/bk-iam/releases/tag/v1.12.10 https://github.com/TencentBlueKing/bk-iam-search-engine/releases/tag/v1.1.2

已添加

2024-03-14 07:26 UTC, jsonwan approved these changes

2024-03-14 07:26 UTC, merged