perf: Job中的主机根据其对应业务的灰度情况展示Agent状态 #2492
TencentBlueKing/bk-job pull request #2536
Opened 2023-10-22 12:11 UTC by jsonwan

1. 默认使用[优先采用AgentId]策略；
2. 支持通过特性[agentStatusGseV2]配置按业务灰度展示；
3. 重构部分代码，补充trace跨线程数据。

2023-10-23 04:00 UTC, wangyu096 requested changes

2023-10-23 07:49 UTC, jsonwan commented on src/backend/commons/common-service/src/main/java/com/tencent/bk/job/common/service/feature/strategy/JobInstanceAttrToggleStrategy.java
> +            Object isAnyAgentV2AvailableObj = ctx.getParam(CTX_PARAM_IS_ANY_GSE_V2_AGENT_AVAILABLE);
已修改为assertRequireParam模式

2023-10-23 14:31 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/config/GseConfig.java
> +    public AgentStateClient useV2ByFeatureAgentStateClient(AgentStateQueryConfig agentStateQueryConfig,
已修改

2023-10-24 02:33 UTC, wangyu096 requested changes

2023-10-24 02:33 UTC, wangyu096 commented on src/backend/commons/common-service/src/main/java/com/tencent/bk/job/common/service/feature/strategy/JobInstanceAttrToggleStrategy.java
> +    private void assertRequireParam(FeatureExecutionContext ctx, String paramName) {
AbstractToggleStrategy 中已经有类似的方法了，通用逻辑可以放在父类中实现

2023-10-24 02:33 UTC, wangyu096 commented on src/backend/commons/common-service/src/main/java/com/tencent/bk/job/common/service/feature/strategy/JobInstanceAttrToggleStrategy.java
> +            assertRequireParam(ctx, CTX_PARAM_OPERATOR);
assert建议放在方法的最前面，强制要求上下文里边完整的传入这些参数，避免用户改配置之后才执行到，运行时才被发现

2023-10-24 02:33 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/config/GseConfig.java
> +    @Bean(DefaultBeanNames.AUTO_CHOOSING_AGENT_STATE_CLIENT)
job-execute 和 job-manage 模块的 GseConfig.java 都有同名 bean，会导致 job-assemble 模块启动失败。AgentStateClient bean 的配置建议放在 gse-sdk模块

2023-10-24 02:57 UTC, jsonwan commented on src/backend/commons/common-service/src/main/java/com/tencent/bk/job/common/service/feature/strategy/JobInstanceAttrToggleStrategy.java
> +    private void assertRequireParam(FeatureExecutionContext ctx, String paramName) {
已修改

2023-10-24 03:04 UTC, jsonwan commented on src/backend/commons/common-service/src/main/java/com/tencent/bk/job/common/service/feature/strategy/JobInstanceAttrToggleStrategy.java
> +            assertRequireParam(ctx, CTX_PARAM_OPERATOR);
这里是运行时的校验，不是初始化参数，运行时才传进来，应该没法提前校验。

2023-10-24 03:11 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/config/GseConfig.java
> +    @Bean(DefaultBeanNames.AUTO_CHOOSING_AGENT_STATE_CLIENT)
同名Bean已处理；
- AgentStateClient bean 的配置建议放在 gse-sdk模块：
公共Bean已放在gse-sdk模块，依赖主机业务Service的Bean才在具体服务中装配的

2023-10-24 09:09 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/config/GseConfig.java
> +    @Bean(DefaultBeanNames.AUTO_CHOOSING_AGENT_STATE_CLIENT)
已当面沟通。

2023-10-24 09:09 UTC, merged