perf: 容器化Values暴露定时任务独立DB等生产环境需要的配置项 #2551
TencentBlueKing/bk-job pull request #2582
Opened 2023-11-05 09:03 UTC by jsonwan

1. 暴露容器化部署需要的相关配置项；
2. 去除冗余的Quartz相关配置。

2023-11-06 02:52 UTC, wangyu096 requested changes

2023-11-06 02:52 UTC, wangyu096 commented on support-files/kubernetes/charts/bk-job/templates/job-crontab/configmap.yaml
> +                threadCount: {{ .Values.crontabConfig.quartz.workThreadCount }}
参数命名，需要要上一级的 threadPool 上下文加入，会更完整一些，避免后续跟其他地方冲突

2023-11-06 02:52 UTC, wangyu096 commented on support-files/kubernetes/charts/bk-job/templates/job-crontab/configmap.yaml
> +                batchTriggerAcquisitionMaxCount: {{ .Values.crontabConfig.quartz.batchTriggerAcquisitionMaxCount }}
参数命名，需要要上一级的 scheduler 上下文加入，会更完整一些，避免后续跟其他地方冲突

2023-11-06 02:52 UTC, wangyu096 commented on support-files/kubernetes/charts/bk-job/values.yaml
> +    workThreadCount: 300
默认值可以小一些？大多数环境用不上 300

2023-11-06 02:53 UTC, wangyu096 commented
job-asemble 模块的配置也需要同步调整

2023-11-06 07:54 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/templates/job-crontab/configmap.yaml
> +                threadCount: {{ .Values.crontabConfig.quartz.workThreadCount }}
已修改

2023-11-06 07:54 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/templates/job-crontab/configmap.yaml
> +                batchTriggerAcquisitionMaxCount: {{ .Values.crontabConfig.quartz.batchTriggerAcquisitionMaxCount }}
已修改

2023-11-06 07:54 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/values.yaml
> +    workThreadCount: 300
已改为50

2023-11-06 12:36 UTC, jsonwan commented
> job-asemble 模块的配置也需要同步调整

已修改

2023-11-07 06:19 UTC, wangyu096 approved these changes

2023-11-07 06:28 UTC, merged