perf: 提供步骤详情与步骤执行结果查询的APIGW接口 #2596
TencentBlueKing/bk-job pull request #2616
Opened 2023-11-14 12:54 UTC by jsonwan

1. 编写接口文档；
2. 接口实现，文档调整。

2023-11-15 03:22 UTC, wangyu096 requested changes

2023-11-15 03:22 UTC, wangyu096 commented on docs/apidoc/bk-api-gateway/v3/zh/get_step_instance_detail.md
> +| bk_scope_id            | string    | 是     | 资源范围ID, 与bk_scope_type对应, 表示业务ID或者业务集ID |
需要传入 job_instance_id 这个父资源 ID

2023-11-15 03:22 UTC, wangyu096 commented on docs/apidoc/bk-api-gateway/v3/zh/get_step_instance_status.md
> +| bk_scope_id            | string    | 是     | 资源范围ID, 与bk_scope_type对应, 表示业务ID或者业务集ID |
需要传入 job_instance_id

2023-11-15 03:22 UTC, wangyu096 commented on docs/apidoc/bk-api-gateway/v3/zh/get_step_instance_status.md
> +| search_ip              | string    | 否     | 主机IP搜索关键字，只返回主机IP包含该关键字的主机执行状态数据 |
建议换成 search_host_id, 后续尽量不是用 ip 检索，避免后台转换

2023-11-15 03:22 UTC, wangyu096 commented on docs/apidoc/bk-api-gateway/v3/zh/get_step_instance_status.md
> +| ip          | string    | IP        |
没有 ipv6 字段

2023-11-15 03:22 UTC, wangyu096 commented on docs/apidoc/bk-api-gateway/v3/zh/get_step_instance_detail.md
> +| secure_param       | int       | 参数是否为敏感参数：0-不敏感，1-敏感 |
少了 ignore_error 参数

2023-11-15 03:22 UTC, wangyu096 commented on docs/apidoc/bk-api-gateway/v3/zh/get_step_instance_detail.md
> +| path            | string    | 目标路径   |
好像缺少了主机信息？

2023-11-15 03:22 UTC, wangyu096 commented on docs/apidoc/bk-api-gateway/v3/zh/get_step_instance_status.md
> +| keyword                | string    | 否     | 日志搜索关键字，只返回日志中包含该关键字的主机执行状态数据 |
仅脚本步骤支持，需要补充说明

2023-11-15 07:23 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/get_step_instance_detail.md
> +| bk_scope_id            | string    | 是     | 资源范围ID, 与bk_scope_type对应, 表示业务ID或者业务集ID |
已添加

2023-11-15 08:55 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/get_step_instance_status.md
> +| bk_scope_id            | string    | 是     | 资源范围ID, 与bk_scope_type对应, 表示业务ID或者业务集ID |
已添加

2023-11-15 08:56 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/get_step_instance_status.md
> +| search_ip              | string    | 否     | 主机IP搜索关键字，只返回主机IP包含该关键字的主机执行状态数据 |
此处ip是作为搜索条件，用IP更符合使用场景，已同时支持ipv6字段搜索

2023-11-15 09:08 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/get_step_instance_detail.md
> +| secure_param       | int       | 参数是否为敏感参数：0-不敏感，1-敏感 |
已补充

2023-11-15 09:12 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/get_step_instance_status.md
> +| keyword                | string    | 否     | 日志搜索关键字，只返回日志中包含该关键字的主机执行状态数据 |
已补充

2023-11-17 11:41 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/get_step_instance_detail.md
> +| path            | string    | 目标路径   |
已添加

2023-11-24 01:47 UTC, wangyu096 requested changes

2023-11-24 01:47 UTC, wangyu096 commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/model/job/v3/resp/EsbFileStepV3DTO.java
> +    @JsonProperty("is_ignore_error")
is_开头的话，建议值还是用 boolean 比较合适；或者改成 ignore_error: 0/1

2023-11-24 01:47 UTC, wangyu096 commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/model/job/v3/resp/EsbScriptStepV3DTO.java
>      private Integer secureParam;
is_开头的话，建议值还是用 boolean 比较合适

2023-11-24 01:47 UTC, wangyu096 commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/model/job/v3/resp/EsbScriptStepV3DTO.java
> +    @JsonPropertyDescription("Is ignore error")
is_开头的话，建议值还是用 boolean 比较合适

2023-11-24 01:47 UTC, wangyu096 commented on src/backend/job-execute/api-job-execute/src/main/java/com/tencent/bk/job/execute/api/esb/v3/EsbGetStepInstanceDetailV3Resource.java
> +    EsbResp<EsbStepV3DTO> getStepInstanceStatus(
方法命名跟 path 不一致，建议统一（getStepInstanceDetail)

2023-11-24 01:47 UTC, wangyu096 commented on src/backend/job-execute/api-job-execute/src/main/java/com/tencent/bk/job/execute/api/esb/v3/EsbGetStepInstanceStatusV3Resource.java
> +        @RequestParam(value = "execute_count", required = false, defaultValue = "0") Integer executeCount,
execute_count 默认不应该是 0，而是应该返回最近一次执行的状态？似乎更合理一些

2023-11-24 01:47 UTC, wangyu096 commented on src/backend/job-execute/api-job-execute/src/main/java/com/tencent/bk/job/execute/model/esb/v3/EsbStepInstanceDetailV3DTO.java
> +     * 作业步骤ID
作业步骤实例 ID。作业步骤 ID 是值作业模版/执行方案里边的 step_id

2023-11-24 01:47 UTC, wangyu096 commented on src/backend/job-execute/api-job-execute/src/main/java/com/tencent/bk/job/execute/model/esb/v3/EsbStepInstanceDetailV3DTO.java
> +    @JsonInclude(JsonInclude.Include.NON_EMPTY)
NON_NULL 更加准确，虽然两个在当前字段下并没有运行上的差异

2023-11-24 01:47 UTC, wangyu096 commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/impl/FileTransferModeServiceImpl.java
> +    public FileTransferModeEnum getTransferMode(Integer duplicateHandler, Integer notExistPathHandler) {
这种工具方法完全没必要使用 Service, 静态方法即可

2023-11-24 01:47 UTC, wangyu096 commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/impl/StepInstanceValidateServiceImpl.java
> +        if (taskInstanceId == null || taskInstanceId < 1) {
增量 API 基础字段校验，需要使用 spring validator 校验

2023-11-24 01:47 UTC, wangyu096 commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/impl/StepInstanceValidateServiceImpl.java
> +public class StepInstanceValidateServiceImpl implements StepInstanceValidateService {
校验能力应该是属于 StepInstance 这个领域的基本能力，直接在 StepInstanceService 提供即可，不需要重新声明 Service，避免类太多。

2023-11-24 01:47 UTC, wangyu096 commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/esb/v3/EsbGetStepInstanceStatusV3ResourceImpl.java
> +        ValidateResult checkResult = stepInstanceValidateService.checkStepInstance(
增量 API 需要使用更加标准的方式：
1. 校验基础字段，应该用 spring validator
2. 校验资源是否存在，应该放在 Service, Controller 层应该只有一些基础参数校验，参数设置，结果封装等基础功能。

2023-11-24 01:55 UTC, jsonwan commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/model/job/v3/resp/EsbFileStepV3DTO.java
> +    @JsonProperty("is_ignore_error")
已修改

2023-11-24 01:55 UTC, jsonwan commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/model/job/v3/resp/EsbScriptStepV3DTO.java
>      private Integer secureParam;
已修改

2023-11-24 01:55 UTC, jsonwan commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/model/job/v3/resp/EsbScriptStepV3DTO.java
> +    @JsonPropertyDescription("Is ignore error")
已修改

2023-11-24 01:57 UTC, jsonwan commented on src/backend/job-execute/api-job-execute/src/main/java/com/tencent/bk/job/execute/api/esb/v3/EsbGetStepInstanceDetailV3Resource.java
> +    EsbResp<EsbStepV3DTO> getStepInstanceStatus(
已修改

2023-11-24 01:57 UTC, jsonwan commented on src/backend/job-execute/api-job-execute/src/main/java/com/tencent/bk/job/execute/api/esb/v3/EsbGetStepInstanceStatusV3Resource.java
> +        @RequestParam(value = "execute_count", required = false, defaultValue = "0") Integer executeCount,
已修改

2023-11-24 02:16 UTC, jsonwan commented on src/backend/job-execute/api-job-execute/src/main/java/com/tencent/bk/job/execute/model/esb/v3/EsbStepInstanceDetailV3DTO.java
> +     * 作业步骤ID
已修改

2023-11-24 02:16 UTC, jsonwan commented on src/backend/job-execute/api-job-execute/src/main/java/com/tencent/bk/job/execute/model/esb/v3/EsbStepInstanceDetailV3DTO.java
> +    @JsonInclude(JsonInclude.Include.NON_EMPTY)
已修改

2023-11-24 02:22 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/impl/FileTransferModeServiceImpl.java
> +    public FileTransferModeEnum getTransferMode(Integer duplicateHandler, Integer notExistPathHandler) {
已修改

2023-11-24 02:40 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/impl/StepInstanceValidateServiceImpl.java
> +        if (taskInstanceId == null || taskInstanceId < 1) {
已修改

2023-11-24 02:41 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/impl/StepInstanceValidateServiceImpl.java
> +public class StepInstanceValidateServiceImpl implements StepInstanceValidateService {
此处校验逻辑需要在多个接口中复用，因此抽象出来

2023-11-24 02:43 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/api/esb/v3/EsbGetStepInstanceStatusV3ResourceImpl.java
> +        ValidateResult checkResult = stepInstanceValidateService.checkStepInstance(
已修改

2023-11-27 01:49 UTC, wangyu096 requested changes

2023-11-27 01:58 UTC, jsonwan commented on src/backend/job-execute/api-job-execute/src/main/java/com/tencent/bk/job/execute/api/esb/v3/EsbGetStepInstanceDetailV3Resource.java
> +        @Positive(message = "{validation.constraints.InvalidJobInstanceId.message}")
已修改

2023-11-27 01:58 UTC, jsonwan commented on src/backend/job-execute/api-job-execute/src/main/java/com/tencent/bk/job/execute/api/esb/v3/EsbGetStepInstanceDetailV3Resource.java
> +        @Positive(message = "{validation.constraints.InvalidStepInstanceId.message}")
已修改

2023-11-27 01:58 UTC, jsonwan commented on src/backend/job-execute/api-job-execute/src/main/java/com/tencent/bk/job/execute/api/esb/v3/EsbGetStepInstanceStatusV3Resource.java
> +        @Positive(message = "{validation.constraints.InvalidJobInstanceId.message}")
已修改

2023-11-27 01:58 UTC, jsonwan commented on src/backend/job-execute/api-job-execute/src/main/java/com/tencent/bk/job/execute/api/esb/v3/EsbGetStepInstanceStatusV3Resource.java
> +        @Positive(message = "{validation.constraints.InvalidStepInstanceId.message}")
已修改

2023-11-27 02:37 UTC, wangyu096 approved these changes

2023-12-07 02:56 UTC, merged