feature: ESB 网关认证参数标准化 #2590
TencentBlueKing/bk-job pull request #2617
Opened 2023-11-15 09:10 UTC by wangyu096

1. 统一认证方式，使用 Authorization 替换原先的 Request Body 中的认证信息
2. CMDB、CMSI、LOGIN、USERMANAGER、GSE ApiClient 重构
3. 统一 ESB、蓝鲸网关调用的 ApiClient基础实现类为  AbstractBkApiClient
4. 删除解析job API 调用方传入认证信息（app_code/app_secret/bk_username)的方式，统一使用从 Esb JWT 中解析出来的认证数据，通过 job-gateway 设置 Header （JobCommonHeaders.USERNAME、JobCommonHeaders.APP_CODE)传递给微服务

2023-11-16 08:59 UTC, jsonwan commented on src/backend/commons/cmdb-sdk/src/main/java/com/tencent/bk/job/common/cc/sdk/BizCmdbClient.java
> +            ResourceWatchReq.class);
换行格式不正确

2023-11-16 09:11 UTC, jsonwan commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/model/BkApiAuthorization.java
文件头未添加开源协议声明，其余文件也存在该问题

2023-11-16 09:46 UTC, jsonwan commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/sdk/AbstractBkApiClient.java
> +            requestInfo.getBody(), null, null, 0, false);
换行格式不正确，其余地方也存在

2023-11-16 09:54 UTC, jsonwan requested changes
一些小问题需要处理

2023-11-17 01:29 UTC, wangyu096 commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/metrics/EsbMetricTags.java
> +    public static final String VALUE_STATUS_OK = "ok";
1. 已确认，未被监控面板引用
2. 所有 Open API， 只有这里是特殊的，需要统一起来

2023-11-17 01:33 UTC, wangyu096 commented on src/backend/commons/cmdb-sdk/src/main/java/com/tencent/bk/job/common/cc/sdk/BizCmdbClient.java
> +            ResourceWatchReq.class);
已修改

2023-11-17 01:35 UTC, wangyu096 commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/sdk/AbstractBkApiClient.java
> +            requestInfo.getBody(), null, null, 0, false);
已修改

2023-11-17 02:04 UTC, wangyu096 commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/model/BkApiAuthorization.java
已修改。

2023-11-17 04:03 UTC, jsonwan commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/metrics/EsbMetricTags.java
> +    public static final String VALUE_STATUS_OK = "ok";
ok

2023-11-17 04:03 UTC, jsonwan approved these changes

2023-11-17 04:11 UTC, merged