feature: 对接蓝鲸消息通知中心 #2659
TencentBlueKing/bk-job pull request #2672
Opened 2023-12-15 10:13 UTC by jsonwan

2023-12-19 07:07 UTC, wangyu096 requested changes

2023-12-19 07:07 UTC, wangyu096 commented on src/backend/commons/common-i18n/src/main/java/com/tencent/bk/job/common/i18n/locale/LocaleUtils.java
> +    public static final String BK_LANG_ZH = "zh";
BK_LANG_XX 跟 LANG_XX 的区别是啥？这里放在一起容易混淆。

建议如果这两种类型的 LANG 是用在不同的地方，是否可以放到不同的类里边加以区分？或者加上注释

2023-12-19 07:07 UTC, wangyu096 commented on src/backend/commons/common-service/src/main/resources/logback-default.xml
> +    <appender name="notice-appender" class="ch.qos.logback.core.rolling.RollingFileAppender">
这个通知模块只有 job-manage 涉及，放在 job-manage 的 logback 配置下可能更合适？放在公共的配置，每个微服务下都会生成  notice.log

2023-12-19 07:09 UTC, wangyu096 commented
job-assemble 没有处理，比如配置

2023-12-19 07:10 UTC, wangyu096 commented
对接消息中心是否是强依赖？如果没有消息中心的话，服务是否能够正常运行？这点需要确认下

2023-12-19 07:15 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/runner/RegisterBkNoticeRunner.java
> + * 进程启动时立即执行一次无效主机清理
已修改

2023-12-19 07:54 UTC, jsonwan commented on src/backend/commons/common-i18n/src/main/java/com/tencent/bk/job/common/i18n/locale/LocaleUtils.java
> +    public static final String BK_LANG_ZH = "zh";
已抽取出单独的常量类

2023-12-19 07:55 UTC, jsonwan commented
> 对接消息中心是否是强依赖？如果没有消息中心的话，服务是否能够正常运行？这点需要确认下

非强依赖，已在jobv3环境验证

2023-12-19 08:03 UTC, jsonwan commented on src/backend/commons/common-service/src/main/resources/logback-default.xml
> +    <appender name="notice-appender" class="ch.qos.logback.core.rolling.RollingFileAppender">
已修改

2023-12-19 08:35 UTC, jsonwan commented
> job-assemble 没有处理，比如配置

只新增了公共配置项，job-assemble也能引用到，没有单独微服务的配置，因此无需处理。

2023-12-20 07:04 UTC, wangyu096 requested changes

2023-12-20 07:04 UTC, wangyu096 commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/config/BkApiGatewayProperties.java
> +    private GseApiGwConfig bkNotice;
GseApiGwConfig 与 bkNotice 不匹配。可能需要改下 GseApiGwConfig 的类名，更加通用一些

2023-12-20 07:04 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/runner/RegisterBkNoticeRunner.java
> +            int affectedNum = globalSettingDAO.upsertGlobalSetting(buildRegisterResult(registerSuccess));
多个实例一起执行可能有并发问题，导致注册结果被覆盖

2023-12-20 07:06 UTC, wangyu096 commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/runner/RegisterBkNoticeRunner.java
> +            int affectedNum = globalSettingDAO.upsertGlobalSetting(buildRegisterResult(registerSuccess));
可以改为注册成功才写入，也可以避免并发问题

2023-12-20 07:26 UTC, jsonwan commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/config/BkApiGatewayProperties.java
> +    private GseApiGwConfig bkNotice;
已修改为ApiGwConfig

2023-12-20 07:26 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/runner/RegisterBkNoticeRunner.java
> +            int affectedNum = globalSettingDAO.upsertGlobalSetting(buildRegisterResult(registerSuccess));
已修改

2023-12-20 07:48 UTC, wangyu096 approved these changes

2023-12-20 08:10 UTC, merged