perf: 作业执行日志量太大导致请求 job-logsvr 服务超时 #2549
TencentBlueKing/bk-job pull request #2702
Opened 2023-12-26 11:05 UTC by liuliaozhong

2024-01-29 06:24 UTC, wangyu096 requested changes

2024-01-31 03:34 UTC, liuliaozhong commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/impl/LogServiceImpl.java
> +    private static final int batchSizeThreshold = 1024 * 1024;
已修改

2024-01-31 03:34 UTC, liuliaozhong commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/impl/LogServiceImpl.java
> +                log.debug("The current script log is too large, exceeding {}, and should be saved in batches, " +
已加

2024-01-31 03:38 UTC, liuliaozhong commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/impl/LogServiceImpl.java
> +            long logSize = calculateLogSize(hostLogDTO);
ServiceScriptLogDTO对象新增了logSize属性，用于记录计算结果

2024-01-31 10:02 UTC, wangyu096 requested changes

2024-01-31 13:19 UTC, liuliaozhong commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/impl/LogServiceImpl.java
> +    @Value("${job.execute.scriptLog.requestContentSizeThreshold:134217728}")
已修改

2024-02-01 01:53 UTC, wangyu096 approved these changes

2024-02-02 02:53 UTC, merged