feat: 提供查询Job当前最新服务版本号的ESB接口 #1976
TencentBlueKing/bk-job pull request #2727
Opened 2024-01-09 13:27 UTC by liuliaozhong

2024-01-11 12:17 UTC, jsonwan commented
需要同步添加APIGW对应接口的文档。

2024-01-11 12:19 UTC, jsonwan commented
版本号比较的实现逻辑较为复杂，可以先看看能否优化，实际上将版本号用.或-分割为几块后逐一比较即可，应该用不着写这么多实现代码。

2024-01-12 03:46 UTC, liuliaozhong commented
> 需要同步添加APIGW对应接口的文档。

已添加

2024-01-12 03:50 UTC, liuliaozhong commented
> 版本号比较的实现逻辑较为复杂，可以先看看能否优化，实际上将版本号用.或-分割为几块后逐一比较即可，应该用不着写这么多实现代码。

已有比较工具CompareUtil，复用已有的

2024-01-18 08:51 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/get_latest_service_version.md
> +- POST
纯查询请求，改为GET更合适

2024-01-18 08:52 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/get_latest_service_version.md
> +}
示例内容也需改为GET示例

2024-01-18 08:57 UTC, jsonwan commented on docs/apidoc/esb/jobv3-confapis/job.yaml
> +  suggest_method: POST
建议改为GET

2024-01-18 08:57 UTC, jsonwan commented on docs/apidoc/esb/jobv3-confapis/job.yaml
> +  dest_http_method: POST
建议改为GET

2024-01-18 09:06 UTC, jsonwan commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/api/esb/v3/EsbServiceInfoV3Resource.java
> +    @PostMapping("/get_latest_service_version")
建议改为GET

2024-01-18 09:09 UTC, jsonwan requested changes
1个小问题需处理

2024-01-18 09:24 UTC, liuliaozhong commented on src/backend/job-manage/api-job-manage/src/main/java/com/tencent/bk/job/manage/api/esb/v3/EsbServiceInfoV3Resource.java
> +    @PostMapping("/get_latest_service_version")
ESB是不是不支持GET请求

2024-01-18 13:39 UTC, liuliaozhong commented on docs/apidoc/bk-api-gateway/v3/zh/get_latest_service_version.md
> +- POST
已改

2024-01-18 13:40 UTC, liuliaozhong commented on docs/apidoc/esb/jobv3-confapis/job.yaml
> +  suggest_method: POST
esb不支持get请求

2024-01-18 13:43 UTC, jsonwan approved these changes

2024-01-18 13:43 UTC, merged