feature: 添加删除定时任务的ESB/APIGW接口 #2733
TencentBlueKing/bk-job pull request #2737
Opened 2024-01-17 10:19 UTC by liuliaozhong

2024-01-18 09:19 UTC, jsonwan commented on src/backend/commons/common-i18n/src/main/resources/i18n/exception/message.properties
> +1245008=删除定时任务失败
错误信息过于笼统，用户无法得到有效信息，只能向平台求助，增加排查成本，需要细化。

2024-01-18 09:23 UTC, jsonwan commented on src/backend/job-crontab/api-job-crontab/src/main/java/com/tencent/bk/job/crontab/model/esb/v3/request/EsbDeleteCronV3Request.java
> +    @NotEmpty(message = "{validation.constraints.CronId_empty.message}")
缺少对应的国际化资源

2024-01-26 10:03 UTC, jsonwan requested changes
1个小问题需要处理，此外，请补充api-gateway接口文档

2024-01-26 12:14 UTC, jsonwan approved these changes

2024-01-26 12:15 UTC, jsonwan commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages_en.properties
> +validation.constraints.CronId_empty.message=Cron id cannot be empty
empty还是改成null吧，与NotNull对应起来

2024-01-26 12:16 UTC, jsonwan requested changes
empty改为null

2024-01-29 09:02 UTC, liuliaozhong commented on src/backend/commons/common-i18n/src/main/resources/i18n/validation/ValidationMessages_en.properties
> +validation.constraints.CronId_empty.message=Cron id cannot be empty
已修改

2024-01-29 09:25 UTC, jsonwan approved these changes

2024-01-29 09:26 UTC, merged