perf: 在服务启动日志中打印版本信息 #1839
TencentBlueKing/bk-job pull request #2742
Opened 2024-01-19 08:25 UTC by liuliaozhong

2024-01-26 12:12 UTC, jsonwan reviewed
commons:common这个模块是基础公共模块，需要看下放在这里面对upgrader和k8s-startup-controller是否有影响

2024-01-31 13:19 UTC, liuliaozhong commented
> commons:common这个模块是基础公共模块，需要看下放在这里面对upgrader和k8s-startup-controller是否有影响

验证过了，不影响upgrader、k8s-startup-controller执行

2024-02-01 02:51 UTC, jsonwan requested changes
1个小问题需要处理

2024-02-01 02:51 UTC, jsonwan commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/VersionInfoLogApplicationRunner.java
> +    @Value("${spring.application.name}")
建议加个默认值，非关键逻辑避免影响主流程

2024-02-01 03:17 UTC, liuliaozhong commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/VersionInfoLogApplicationRunner.java
> +    @Value("${spring.application.name}")
已添加

2024-02-01 03:21 UTC, jsonwan approved these changes

2024-02-01 03:22 UTC, merged