perf: 执行日志导出代码优化 #1601
TencentBlueKing/bk-job pull request #2752
Opened 2024-01-25 11:21 UTC by liuliaozhong

2024-01-26 12:40 UTC, jsonwan commented
![企业微信截图_17062728045073](https://github.com/TencentBlueKing/bk-job/assets/53823124/8d856c1f-fd63-47bf-8cd9-ff56e539f13a)
有个格式问题需要处理下

2024-01-26 12:42 UTC, jsonwan commented
另外，这里最好是能够用上traceId一次性检索出所有关联日志，请先部署到联合开发环境，需要上去看下优化效果，或者grep出关联日志截个图放这里也行

2024-02-20 11:52 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/impl/LogExportServiceImpl.java
> +        log.info("Package log file for {}|{}|{}|{}|{}|{}|{}|{}", username, appId, stepInstanceId, hostId, executeCount,
建议在区分度不清晰的占位符前加上key的名称，例如appId={}|stepInstanceId={}...，否则排查问题时必须结合代码才能进行，效率大幅降低，其他地方也检查下

2024-02-20 11:52 UTC, jsonwan requested changes
1个问题需要修改

2024-02-20 12:19 UTC, liuliaozhong commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/impl/LogExportServiceImpl.java
> +        log.info("Package log file for {}|{}|{}|{}|{}|{}|{}|{}", username, appId, stepInstanceId, hostId, executeCount,
已改

2024-02-20 12:29 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/impl/LogExportServiceImpl.java
> +                        executeCount, e);
这里的异常堆栈打印不出来，参考其他地方异常堆栈的打印方式，用MessageFormatter先格式化错误信息。
只有调用到这个方法才能打印出堆栈：public void error(String msg, Throwable t);

2024-02-20 12:29 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/impl/LogExportServiceImpl.java
> +                    log.debug("Process finished!|stepInstanceId={}|logFileName={}", stepInstanceId,
占位符数量与参数数量不匹配

2024-02-20 12:30 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/impl/LogExportServiceImpl.java
> +        log.info("Package log success.|stepInstanceId={}|logFileName={}", stepInstanceId, logFileName);
executeCount表示重试次数，不应该去掉吧

2024-02-20 12:31 UTC, jsonwan requested changes
3个问题需要处理

2024-02-20 12:46 UTC, jsonwan approved these changes

2024-02-20 12:47 UTC, merged