perf: 当业务不存在后，对于在JOB的周期性任务是否应该停止的处理机制 #621
TencentBlueKing/bk-job pull request #2779
Opened 2024-02-21 03:56 UTC by liuliaozhong

2024-02-27 04:05 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/sync/BizSetEventWatcher.java
> +                    serviceCronJobResource.disabledCronJobByAppId(cachedApp.getId());
不建议立即disable，依赖定时巡检去disable就行了，一开始只需要让已删除业务的定时任务不执行即可，过一段时间再去disable。如果CMDB故障产生了一波异常的业务删除事件，并且Job这边立即disable了对应的定时任务的话，故障恢复后Job这边还需要去恢复定时任务数据，增加无谓的工作量，所以留一个缓冲期比较好。

2024-02-27 04:05 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/sync/BizEventWatcher.java
> +                    serviceCronJobResource.disabledCronJobByAppId(cachedApp.getId());
不建议立即disable，依赖定时巡检去disable就行了，一开始只需要让已删除业务的定时任务不执行即可，过一段时间再去disable。如果CMDB故障产生了一波异常的业务删除事件，并且Job这边立即disable了对应的定时任务的话，故障恢复后Job这边还需要去恢复定时任务数据，增加无谓的工作量，所以留一个缓冲期比较好。

2024-02-27 06:30 UTC, jsonwan commented on src/backend/job-crontab/api-job-crontab/src/main/java/com/tencent/bk/job/crontab/api/inner/ServiceCronJobResource.java
> +    InternalResponse<Boolean> disabledCronJobByAppId(
结合后面的Review意见看，这个接口应该是不需要的

2024-02-27 06:31 UTC, jsonwan commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/service/CronJobService.java
> +    boolean disabledCronJobByAppId(Long appId);
命名不太规范，disabled是形容词，建议改为disable动词

2024-02-27 06:41 UTC, jsonwan commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/service/impl/CronJobServiceImpl.java
> +    @JobTransactional(transactionManager = "jobCrontabTransactionManager")
事务范围过大，可能造成长事务引起DB告警

2024-02-27 06:41 UTC, jsonwan commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/service/impl/CronJobServiceImpl.java
> +        log.info("cron job will be disabled, appId:{}, size:{}", appId, cronJobDTOList.size());
建议把受影响的ID也都打印出来

2024-02-27 06:46 UTC, jsonwan commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/service/impl/CronJobServiceImpl.java
> +            changeCronJobEnableStatus(JobConstants.DEFAULT_SYSTEM_USER_ADMIN, appId,
返回值可在后续日志中打印出来

2024-02-27 06:55 UTC, jsonwan commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/task/DisableCronJobWithBizNotExistTask.java
> + * 当业务不存在后，禁用定时任务
“不存在”这个描述不太准确，一开始业务是存在的，只是后面被归档了，用“被归档”更合适

2024-02-27 07:06 UTC, jsonwan commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/task/DisableCronJobWithBizNotExistTask.java
> +    @Value("${job.crontab.disableCron.enabled:true}")
配置项不准确，建议改为job.crontab.autoDisableCronOfArchivedScope.enabled

2024-02-27 07:07 UTC, jsonwan commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/task/DisableCronJobWithBizNotExistTask.java
> +    private Boolean enable;
建议改为enabled

2024-02-27 07:08 UTC, jsonwan commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/task/DisableCronJobWithBizNotExistTask.java
> +            log.info("disableCronJobWithBizNotExistTask not enabled, skip, you can enable it in config file");
名称需要相应调整，其他地方也检查下

2024-02-27 07:22 UTC, jsonwan commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/task/DisableCronJobWithBizNotExistTask.java
> +            List<ApplicationDTO> ccAllBizApps = bizCmdbClient.getAllBizApps();
查询业务（集）在CMDB是否存在的方式需要优化一下：把需要查询的ID作为搜索条件去查询，而非查出全量信息再来对比，涉及到全量的操作都要注意下，非必要不全量，减小内存溢出风险。

2024-02-27 07:35 UTC, jsonwan commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/task/ScheduledTasks.java
> +    @Scheduled(cron = "0 0 2 * * ?")
建议放在早上9:00，如果引发什么问题方便工作时间处理

2024-02-27 07:38 UTC, jsonwan commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/task/ScheduledTasks.java
> +    public void disableCronJob() {
命名建议改准确点，因为很多时候只看日志是缺少上下文的，所以尽量清晰，减少阅读代码排查问题的成本

2024-02-27 07:41 UTC, jsonwan commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/timer/executor/SimpleJobExecutor.java
> +            ServiceApplicationDTO serviceApplicationDTO = applicationResource.queryAppById(appId);
这里的耗时是直接计入“任务执行延迟”这个指标的，需要尽可能短，建议优化为用exists判断的方式，服务接口调用只返回布尔值即可。

2024-02-27 07:43 UTC, jsonwan requested changes
有几个问题需要处理。

2024-02-28 11:53 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/sync/BizSetEventWatcher.java
> +                    serviceCronJobResource.disabledCronJobByAppId(cachedApp.getId());
代码已去掉

2024-02-28 11:54 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/service/impl/sync/BizEventWatcher.java
> +                    serviceCronJobResource.disabledCronJobByAppId(cachedApp.getId());
代码已去掉

2024-02-28 11:54 UTC, liuliaozhong commented on src/backend/job-crontab/api-job-crontab/src/main/java/com/tencent/bk/job/crontab/api/inner/ServiceCronJobResource.java
> +    InternalResponse<Boolean> disabledCronJobByAppId(
已处理

2024-02-28 11:54 UTC, liuliaozhong commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/service/CronJobService.java
> +    boolean disabledCronJobByAppId(Long appId);
已改

2024-02-28 11:54 UTC, liuliaozhong commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/service/impl/CronJobServiceImpl.java
> +        List<CronJobInfoDTO> cronJobDTOList = listPageCronJobInfos(cronJobInfoDTO,
已改成只查ID

2024-02-28 11:55 UTC, liuliaozhong commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/service/impl/CronJobServiceImpl.java
> +    @JobTransactional(transactionManager = "jobCrontabTransactionManager")
去掉了，changeCronJobEnableStatus方法有事务

2024-02-28 11:55 UTC, liuliaozhong commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/service/impl/CronJobServiceImpl.java
> +        log.info("cron job will be disabled, appId:{}, size:{}", appId, cronJobDTOList.size());
已改

2024-02-28 11:55 UTC, liuliaozhong commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/service/impl/CronJobServiceImpl.java
> +            changeCronJobEnableStatus(JobConstants.DEFAULT_SYSTEM_USER_ADMIN, appId,
已改

2024-02-28 11:56 UTC, liuliaozhong commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/task/DisableCronJobWithBizNotExistTask.java
> + * 当业务不存在后，禁用定时任务
已改

2024-02-28 11:56 UTC, liuliaozhong commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/task/DisableCronJobWithBizNotExistTask.java
> +    @Value("${job.crontab.disableCron.enabled:true}")
已改

2024-02-28 11:56 UTC, liuliaozhong commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/task/DisableCronJobWithBizNotExistTask.java
> +    private Boolean enable;
已改

2024-02-28 11:56 UTC, liuliaozhong commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/task/DisableCronJobWithBizNotExistTask.java
> +    private void disableCronJob() {
已改

2024-02-28 11:58 UTC, liuliaozhong commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/task/DisableCronJobWithBizNotExistTask.java
> +            List<ApplicationDTO> ccAllBizApps = bizCmdbClient.getAllBizApps();
已优化，按业务(集)ids为查询条件从cmdb查询

2024-02-28 11:58 UTC, liuliaozhong commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/task/ScheduledTasks.java
> +    @Scheduled(cron = "0 0 2 * * ?")
已改

2024-02-28 11:58 UTC, liuliaozhong commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/timer/executor/SimpleJobExecutor.java
> +            ServiceApplicationDTO serviceApplicationDTO = applicationResource.queryAppById(appId);
已优化

2024-03-06 02:34 UTC, jsonwan commented on src/backend/commons/cmdb-sdk/src/main/java/com/tencent/bk/job/common/cc/sdk/BizCmdbClient.java
> +            log.error("Query biz from cmdb through bizIds, return data is null, bizIdz={}", bizIds);
日志级别不正确，被归档的业务ID在CMDB查不到是一种正常的场景，此处用info更合适

2024-03-06 02:50 UTC, jsonwan commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/service/impl/CronJobServiceImpl.java
> +            if (log.isDebugEnabled()) {
debug打印执行前没有耗时操作的话这个判断是不需要的，debug方法内本身会判断，确定要打印才会做参数替换

2024-03-06 02:52 UTC, jsonwan commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/service/impl/CronJobServiceImpl.java
> +            Boolean disableResult = changeCronJobEnableStatus(JobConstants.DEFAULT_SYSTEM_USER_ADMIN, appId,
1. 单个任务操作建议捕获异常，不影响后续任务继续；
2. 该结果为false时建议纳入统计数据，结束后如果失败数量不为0则用一条日志打印出来，并指出是哪些ID失败了。

2024-03-06 02:58 UTC, jsonwan commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/task/DisableCronJobOfArchivedScopeTask.java
> +            cronJobService.disableCronJobByAppId(appId);
执行结果是需要统计并在后续总结日志中打印的

2024-03-06 03:00 UTC, jsonwan commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/task/DisableCronJobOfArchivedScopeTask.java
> +        log.info("cron job disabled successfully");
这句日志不准确，无法表达失败与部分成功的结果，需要结合统计数据打印，全部成功，一条INFO日志即可，存在失败，则需要WARN日志

2024-03-06 03:14 UTC, jsonwan commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/task/ScheduledTasks.java
> +            JobContextUtil.setRequestId(UUID.randomUUID().toString());
如果只是用于在日志中生成traceId的话，可以尝试使用Spring Cloud Sleuth提供的@NewSpan注解来替代当前方式

2024-03-06 03:18 UTC, jsonwan commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/inner/impl/ServiceApplicationResourceImpl.java
> +            log.error("biz/bizSet not exist, appId={}", appId);
日志级别不正确，appId不存在是正常的场景，建议INFO

2024-03-06 03:20 UTC, jsonwan requested changes
几个小问题需要处理下。

2024-03-06 03:20 UTC, jsonwan commented
代码冲突请处理下。

2024-03-06 13:01 UTC, liuliaozhong commented
> 代码冲突请处理下。

已处理

2024-03-06 13:02 UTC, liuliaozhong commented on src/backend/job-manage/service-job-manage/src/main/java/com/tencent/bk/job/manage/api/inner/impl/ServiceApplicationResourceImpl.java
> +            log.error("biz/bizSet not exist, appId={}", appId);
已改

2024-03-06 13:17 UTC, liuliaozhong commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/task/ScheduledTasks.java
> +            JobContextUtil.setRequestId(UUID.randomUUID().toString());
已删。主要是我在别的分支测试时发现获取分布式锁是通过JobContextUtil.getRequestId()获取的请求Id，在master分支不需要了

2024-03-06 13:17 UTC, liuliaozhong commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/task/DisableCronJobOfArchivedScopeTask.java
> +        log.info("cron job disabled successfully");
已改

2024-03-06 13:17 UTC, liuliaozhong commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/service/impl/CronJobServiceImpl.java
> +            Boolean disableResult = changeCronJobEnableStatus(JobConstants.DEFAULT_SYSTEM_USER_ADMIN, appId,
已优化

2024-03-06 13:17 UTC, liuliaozhong commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/service/impl/CronJobServiceImpl.java
> +            if (log.isDebugEnabled()) {
已删除

2024-03-06 13:18 UTC, liuliaozhong commented on src/backend/commons/cmdb-sdk/src/main/java/com/tencent/bk/job/common/cc/sdk/BizCmdbClient.java
> +            log.error("Query biz from cmdb through bizIds, return data is null, bizIdz={}", bizIds);
已改

2024-03-14 03:42 UTC, jsonwan approved these changes

2024-03-14 03:48 UTC, jsonwan commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/service/impl/CronJobServiceImpl.java
> +        log.info("cron job will be disabled, appId:{}, cronJobIds:{}", appId, cronJobIdList);
建议先判非空再打印，减少无意义的日志

2024-03-14 03:53 UTC, jsonwan commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/task/ScheduledTasks.java
> +    public void disableCronJobTask() {
方法名称建议修改为disableCronJobOfArchivedScopeTask()

2024-03-14 03:53 UTC, jsonwan commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/task/ScheduledTasks.java
> +            log.error("disableCronJobTask fail", e);
相应修改：disableCronJobOfArchivedScopeTask

2024-03-14 03:53 UTC, jsonwan commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/task/ScheduledTasks.java
> +            log.info("disableCronJobTask end, duration={}ms", System.currentTimeMillis() - start);
相应修改：disableCronJobOfArchivedScopeTask

2024-03-14 03:54 UTC, jsonwan requested changes
2个小问题需处理。

2024-03-14 03:54 UTC, jsonwan commented
![image](https://github.com/TencentBlueKing/bk-job/assets/53823124/6b2a2157-a82e-4ea6-9ce2-b36448e0636a)

2024-03-14 06:13 UTC, liuliaozhong commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/service/impl/CronJobServiceImpl.java
> +        log.info("cron job will be disabled, appId:{}, cronJobIds:{}", appId, cronJobIdList);
已判断

2024-03-14 06:13 UTC, liuliaozhong commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/task/ScheduledTasks.java
> +    public void disableCronJobTask() {
已修改

2024-03-14 06:14 UTC, liuliaozhong commented on src/backend/job-crontab/service-job-crontab/src/main/java/com/tencent/bk/job/crontab/task/ScheduledTasks.java
> +            log.info("disableCronJobTask end, duration={}ms", System.currentTimeMillis() - start);
已修改

2024-03-14 07:25 UTC, merged