feat: Job Open API 支持容器执行 #2774
TencentBlueKing/bk-job pull request #2795
Opened 2024-03-06 07:13 UTC by wangyu096

2024-03-13 10:03 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +            "fetch_any_container": true
any含义不清晰，可指代“一些”，建议使用random_one

2024-03-14 02:01 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +| fetch_any_container | boolean | 否 | 是否随机选择一个容器作为执行对象；默认为 false |
any建议修改为random_one，更明确

2024-03-14 02:04 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +| cluster_name_list | array | 否 | 集群名称列表 |
传一个空的列表与不传该字段含义是否一样？

2024-03-14 02:11 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +| kube_node_filters | array | 否 | 容器拓扑节点过滤器列表，多个过滤器为 OR 关系. 过滤器定义见 kube_node_filter |
为什么cluster、namespace和workload的filter要放在node_filters里面而不是平铺单独作为3个filter字段，将来也好扩展（例如按照namespace的label过滤），放在一起比较臃肿，node_filters用来囊括cluster、namespace和workload也不太合理，因为不同workload可能分布在不同node上

2024-03-14 02:13 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +        "host_id_list":
需要与字段定义一致并增加hostId与cloudIp的示例数据

2024-03-14 02:17 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +{
缺少外层error、permission等字段

2024-03-14 02:18 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_batch_get_job_instance_execute_object_log.md
> +{
缺少外层error、permission等字段

2024-03-14 02:18 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_batch_get_job_instance_execute_object_log.md
> +{
缺少外层error、permission等字段

2024-03-14 02:20 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_get_job_instance_status.md
> +{
缺少外层error、permission等字段

2024-03-14 02:25 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_get_job_instance_status.md
> +| error | object | 如果响应的 http code 不为 200/201, error 用于说明错误信息 |
缺少更深层的字段说明

2024-03-14 02:30 UTC, jsonwan requested changes
几个问题需要处理下。

2024-03-14 09:34 UTC, wangyu096 commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +            "fetch_any_container": true
改成 fetch_one_container. 因为我们这里并没有随机的概念，所以不能强调随机

2024-03-14 09:34 UTC, wangyu096 commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +| fetch_any_container | boolean | 否 | 是否随机选择一个容器作为执行对象；默认为 false |
改成 fetch_one_container. 因为我们这里并没有随机的概念，所以不能强调随机

2024-03-14 09:35 UTC, wangyu096 commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +| kube_node_filters | array | 否 | 容器拓扑节点过滤器列表，多个过滤器为 OR 关系. 过滤器定义见 kube_node_filter |
ok

2024-03-14 09:35 UTC, wangyu096 commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +        "host_id_list":
fix

2024-03-14 09:35 UTC, wangyu096 commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_batch_get_job_instance_execute_object_log.md
> +{
fix

2024-03-14 09:35 UTC, wangyu096 commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_get_job_instance_status.md
> +{
fix

2024-03-14 09:36 UTC, wangyu096 commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_get_job_instance_status.md
> +| error | object | 如果响应的 http code 不为 200/201, error 用于说明错误信息 |
fix

2024-03-14 13:41 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +| fetch_any_container | boolean | 否 | 是否随机选择一个容器作为执行对象；默认为 false |
OK

2024-03-14 13:41 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +            "fetch_any_container": true
OK

2024-03-15 03:59 UTC, wangyu096 commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +| cluster_name_list | array | 否 | 集群名称列表 |
会有校验，不允许传入空的 list 或者 null，因为这种设计对用户理解上有歧义

2024-03-15 07:13 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_batch_get_job_instance_execute_object_log.md
> +{
示例数据中的字段仍不完整。

2024-03-15 07:15 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +| fetch_any_one_container | boolean | 否 | 是否随机选择一个容器作为执行对象；默认为 false |
![image](https://github.com/TencentBlueKing/bk-job/assets/53823124/9f85fdc1-8acb-4b0a-9302-5fd465df06d5)
请与答复保持一致

2024-03-15 07:16 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +| kube_container_prop_filter | object | 是 | 容器 container 属性过滤器，过滤器定义见 kube_container_prop_filter |
建议与上面几个filter风格保持一致，去掉prop_

2024-03-15 07:16 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +##### kube_pod_prop_filter
建议去除prop_

2024-03-15 07:17 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +                "kube_container_prop_filter": {
建议去除prop_

2024-03-15 07:17 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +{
字段不完整，所有示例响应数据都需要检查下

2024-03-15 07:19 UTC, jsonwan requested changes
功能满足，几个小的风格问题需调整。

2024-03-15 07:40 UTC, wangyu096 commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +| fetch_any_one_container | boolean | 否 | 是否随机选择一个容器作为执行对象；默认为 false |
维持 fetch_any_one_container 命名，感觉更准确；去掉“随机”这个说明

2024-03-15 07:40 UTC, wangyu096 commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +| kube_container_prop_filter | object | 是 | 容器 container 属性过滤器，过滤器定义见 kube_container_prop_filter |
1. 加上 prop避免与外层 kube_container_filters 歧义
2. 暂时没有想到更合适的命名，等后续再调整

2024-03-15 07:40 UTC, wangyu096 commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +##### kube_pod_prop_filter
加上 prop避免与外层 kube_container_filters 歧义
暂时没有想到更合适的命名，等后续再调整

2024-03-15 07:40 UTC, wangyu096 commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +                "kube_container_prop_filter": {
加上 prop避免与外层 kube_container_filters 歧义
暂时没有想到更合适的命名，等后续再调整

2024-03-15 07:47 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +| kube_container_prop_filter | object | 是 | 容器 container 属性过滤器，过滤器定义见 kube_container_prop_filter |
OK

2024-03-15 07:50 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +                "kube_container_prop_filter": {
OK

2024-03-15 07:50 UTC, jsonwan approved these changes

2024-03-15 07:50 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +| fetch_any_one_container | boolean | 否 | 是否随机选择一个容器作为执行对象；默认为 false |
OK

2024-03-15 07:51 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +##### kube_pod_prop_filter
OK

2024-03-22 07:32 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +| job_instance_name | long | 作业实例名称 |
字段类型不正确

2024-03-26 02:10 UTC, wangyu096 commented on docs/apidoc/bk-api-gateway/v3/zh/bkci_plugin_fast_execute_script.md
> +| job_instance_name | long | 作业实例名称 |
fixed

2024-03-26 03:23 UTC, jsonwan approved these changes

2024-03-26 03:42 UTC, merged