feat: 容器执行支持 label selector 表达式 #2858
TencentBlueKing/bk-job pull request #2864
Opened 2024-04-01 07:38 UTC by wangyu096

2024-04-07 07:27 UTC, jsonwan commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/util/PageUtil.java
> +     * 注意：如果多次分页查询期间元升数据发生变化，使用该方法可能出现数据重复/遗漏的情况。该方法仅使用于对数据准确度要求不高的场景！！！
错别字，“元升”->?，仅使用于->仅适用于

2024-04-07 07:32 UTC, jsonwan commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/util/http/WatchableHttpHelper.java
> +            httpStatus = HttpStatus.SC_INTERNAL_SERVER_ERROR;
值不准确，此处异常可能并非由服务端500导致

2024-04-07 11:41 UTC, jsonwan commented on src/backend/job-logsvr/api-job-logsvr/src/main/java/com/tencent/bk/job/logsvr/api/ServiceLogResource.java
> -    InternalResponse<?> tmpSaveLogs(
建议在下个大版本删除

2024-04-07 11:43 UTC, jsonwan requested changes
几个小问题需处理

2024-04-08 02:54 UTC, wangyu096 commented on src/backend/job-logsvr/api-job-logsvr/src/main/java/com/tencent/bk/job/logsvr/api/ServiceLogResource.java
> -    InternalResponse<?> tmpSaveLogs(
这个版本就可以删除了。原始的就是 /service/log/batch, 后面不小心改成了 /batch 导致发布报错 NOT_FOUND. 后续又改回了 /service/log/batch. 引入这个方法只是为了保证 bkop 环境再次发布不会出异常的规避方案

相当于做了一次 A->B->A的修改。

2024-04-08 02:56 UTC, wangyu096 commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/util/PageUtil.java
> +     * 注意：如果多次分页查询期间元升数据发生变化，使用该方法可能出现数据重复/遗漏的情况。该方法仅使用于对数据准确度要求不高的场景！！！
fixed

2024-04-08 03:19 UTC, wangyu096 commented on src/backend/commons/common/src/main/java/com/tencent/bk/job/common/util/http/WatchableHttpHelper.java
> +            httpStatus = HttpStatus.SC_INTERNAL_SERVER_ERROR;
fixed. 这个时候 http status 设置为 UNKNOWN。参考 spring actuator 的 http_server_requests 实现

2024-04-08 03:41 UTC, jsonwan commented on src/backend/job-logsvr/api-job-logsvr/src/main/java/com/tencent/bk/job/logsvr/api/ServiceLogResource.java
> -    InternalResponse<?> tmpSaveLogs(
OK

2024-04-08 03:42 UTC, jsonwan approved these changes

2024-04-08 03:43 UTC, merged