feat: 增加查询文件源与凭证详情的ApiGW接口 #2830
TencentBlueKing/bk-job pull request #2870
Opened 2024-04-02 10:15 UTC by liuliaozhong

2024-04-07 11:56 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/get_credential_detail.md
> +| id               | string    | 凭据ID                                                       |
统一使用“凭证”，与页面保持一致，其他地方也检查下，有“凭据”的地方都改过来。

2024-04-07 11:56 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/get_credential_detail.md
> +| id            | String | 是   | 凭据ID                                                  |
统一使用“凭证”，与页面保持一致，其他地方也检查下，有“凭据”的地方都改过来。

2024-04-07 12:01 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/get_file_source_detail.md
> +/api/v3/get_file_source_detail?bk_scope_type=biz&bk_scope_id=1&code=1
code=1不太合适，看着像数字，可改为bkrepo-1

2024-04-07 12:01 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/get_file_source_detail.md
> +        "id": 0,
id改为大于0的数字

2024-04-07 13:02 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/get_file_source_detail.md
> +        "file_source_type": 3,
这个字段建议改为文件源类型的code

2024-04-07 13:02 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/get_file_source_detail.md
> +| file_source_type | int    | 类型。可选值：蓝鲸制品库 |
这个字段建议改为文件源类型的code，类型与描述需要相应修改

2024-04-07 13:03 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/get_file_source_detail.md
> +| create_time      | long   | 创建时间，Unix 时间戳                                        |
需要注明单位为ms

2024-04-07 13:03 UTC, jsonwan commented on docs/apidoc/bk-api-gateway/v3/zh/get_file_source_detail.md
> +| last_modify_time | long   | 最后修改时间，Unix 时间戳                                    |
需要注明单位为ms

2024-04-07 13:05 UTC, jsonwan commented on docs/apidoc/esb/jobv3-confapis/apidocs/en/get_credential_detail.md
> +### Function Description
中文文档修改的地方需要同步到英文文档中

2024-04-07 13:08 UTC, jsonwan commented on docs/apidoc/esb/jobv3-confapis/job.yaml
ESB相关改动可去除，只提供ApiGW的接口

2024-04-07 13:50 UTC, jsonwan commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/api/esb/EsbFileSourceV3ResourceImpl.java
> +        FileSourceDTO fileSourceDTO = fileSourceService.getFileSourceByCode(req.getCode());
需要加上appId查询，code仅在appId下唯一，仅使用code获取的地方需要改过来

2024-04-08 03:40 UTC, jsonwan requested changes
几个小问题需要处理下

2024-04-08 13:18 UTC, liuliaozhong commented on docs/apidoc/bk-api-gateway/v3/zh/get_credential_detail.md
> +| id               | string    | 凭据ID                                                       |
已改

2024-04-08 13:18 UTC, liuliaozhong commented on docs/apidoc/bk-api-gateway/v3/zh/get_credential_detail.md
> +| id            | String | 是   | 凭据ID                                                  |
已改

2024-04-08 13:18 UTC, liuliaozhong commented on docs/apidoc/bk-api-gateway/v3/zh/get_file_source_detail.md
> +/api/v3/get_file_source_detail?bk_scope_type=biz&bk_scope_id=1&code=1
已改

2024-04-08 13:19 UTC, liuliaozhong commented on docs/apidoc/bk-api-gateway/v3/zh/get_file_source_detail.md
> +        "id": 0,
已改

2024-04-08 13:19 UTC, liuliaozhong commented on docs/apidoc/bk-api-gateway/v3/zh/get_file_source_detail.md
> +        "file_source_type": 3,
已改

2024-04-08 13:19 UTC, liuliaozhong commented on docs/apidoc/bk-api-gateway/v3/zh/get_file_source_detail.md
> +| file_source_type | int    | 类型。可选值：蓝鲸制品库 |
已改

2024-04-08 13:19 UTC, liuliaozhong commented on docs/apidoc/bk-api-gateway/v3/zh/get_file_source_detail.md
> +| last_modify_time | long   | 最后修改时间，Unix 时间戳                                    |
已改

2024-04-08 13:20 UTC, liuliaozhong commented on docs/apidoc/esb/jobv3-confapis/apidocs/en/get_credential_detail.md
> +### Function Description
已去除

2024-04-08 13:20 UTC, liuliaozhong commented on docs/apidoc/esb/jobv3-confapis/job.yaml
已去除

2024-04-08 13:20 UTC, liuliaozhong commented on src/backend/job-file-gateway/service-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/api/esb/EsbFileSourceV3ResourceImpl.java
> +        FileSourceDTO fileSourceDTO = fileSourceService.getFileSourceByCode(req.getCode());
已修改

2024-04-09 01:54 UTC, jsonwan commented on src/backend/job-file-gateway/api-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/api/inner/ServiceFileSourceResource.java
> +    @GetMapping("/service/app/{appId}/fileSource/getFileSourceIdByCode/codes/{code}")
这里不要直接改接口路径，避免发布时任务异常。
添加一个新的接口，并将老接口标记为Deprecated，在下个大版本再删除，以实现无损发布。

2024-04-09 01:56 UTC, jsonwan requested changes
1个问题需要处理。

2024-04-09 03:08 UTC, liuliaozhong commented on src/backend/job-file-gateway/api-job-file-gateway/src/main/java/com/tencent/bk/job/file_gateway/api/inner/ServiceFileSourceResource.java
> +    @GetMapping("/service/app/{appId}/fileSource/getFileSourceIdByCode/codes/{code}")
已修改

2024-04-09 03:16 UTC, jsonwan approved these changes

2024-04-09 03:16 UTC, merged