fix: 作业使用 GSE V2 管道，当agent_id 不存在的时候，会调用 GSE V1 的 queryAgentStatus API #3013
TencentBlueKing/bk-job pull request #3016
Opened 2024-05-31 03:02 UTC by wangyu096

#3013

2024-05-31 13:39 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/values.yaml
> +      enabled: true
此处是刻意没有加该默认值的，加上此默认值后，默认全部使用GSE 2.0，是否对GSE有版本依赖？即使版本依赖满足，如何保证用户的环境已经全量切换到GSE 2.0，只能优先使用2.0吧

2024-05-31 13:40 UTC, jsonwan requested changes
1个问题需处理。

2024-06-01 08:18 UTC, wangyu096 commented on support-files/kubernetes/charts/bk-job/values.yaml
> +      enabled: true
https://bk.tencent.com/docs/markdown/ZH/VersionLog/7.1/v71.md

2024-06-03 01:35 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/values.yaml
> +      enabled: true
OK

2024-06-03 01:35 UTC, jsonwan approved these changes

2024-06-03 01:37 UTC, merged