feature: AI+JOB 一期 #2995
TencentBlueKing/bk-job pull request #3069
Opened 2024-06-18 12:34 UTC by jsonwan

1. 接口设计、Mock数据。

2024-09-14 04:22 UTC, wangyu096 requested changes

2024-09-14 11:45 UTC, jsonwan commented on support-files/sql/job-analysis/0008_job_analysis_20240618-1000_V3.10.0_mysql.sql
> +USE job_analysis;
已修改

2024-09-14 11:47 UTC, jsonwan commented on src/backend/job-analysis/service-job-analysis/src/main/resources/i18n/message_zh_CN.properties
> +job.analysis.ai.fileTaskErrorSource.noError=任务成功并未失败
已修改为“任务未失败”

2024-09-14 11:48 UTC, jsonwan commented on src/backend/job-analysis/service-job-analysis/src/main/java/com/tencent/bk/job/analysis/util/ai/AIAnswerUtil.java
> +            log.warn(
已修改为INFO

2024-09-14 11:57 UTC, jsonwan commented on src/backend/job-analysis/service-job-analysis/src/main/java/com/tencent/bk/job/analysis/dao/impl/AIChatHistoryDAOImpl.java
> +        Long existStartTime = dslContext.select(defaultTable.START_TIME)
一次查询只能命中一个索引+扫描结果集的所有数据，时间复杂度为O(n)，效率较低，两次查询可全部命中索引，第二次扫描的结果集很小，时间复杂度近似O(1)。

2024-09-14 12:19 UTC, jsonwan commented on src/backend/job-analysis/service-job-analysis/src/main/java/com/tencent/bk/job/analysis/task/ai/AIChatHistoryCleanTask.java
> +            deletedNum = aiChatHistoryDAO.deleteChatHistory(maxId, batchSize);
确实，已修改

2024-09-14 12:27 UTC, jsonwan commented on src/backend/job-analysis/service-job-analysis/src/main/java/com/tencent/bk/job/analysis/task/ai/AIChatHistoryCleanTask.java
> +                ThreadUtils.sleep(100);
一次性删除大量数据可能导致DB高负载，sleep一下可以缓解下负载压力，也在高负载发生时让其他SQL有机会执行。

2024-09-14 12:31 UTC, jsonwan commented on src/backend/job-analysis/service-job-analysis/src/main/java/com/tencent/bk/job/analysis/dao/impl/AIChatHistoryDAOImpl.java
> +        conditions.add(defaultTable.IS_DELETED.eq(JooqDataTypeUtil.buildUByte(0)));
已修改

2024-09-14 12:31 UTC, jsonwan commented on src/backend/job-analysis/service-job-analysis/src/main/java/com/tencent/bk/job/analysis/dao/impl/AIChatHistoryDAOImpl.java
> +            .set(defaultTable.IS_DELETED, JooqDataTypeUtil.buildUByte(1))
已修改

2024-09-14 12:32 UTC, jsonwan commented on src/backend/job-analysis/service-job-analysis/src/main/java/com/tencent/bk/job/analysis/task/ai/AIChatHistoryCleanTask.java
> +        int batchSize = 10000;
已修改

2024-09-14 12:34 UTC, jsonwan commented on src/backend/job-analysis/service-job-analysis/src/main/java/com/tencent/bk/job/analysis/task/ai/AIChatHistoryCleanTask.java
> +        Integer maxKeepDays = aiProperties.getChatHistory().getMaxKeepDays();
任意一个超出就删除。

2024-09-14 12:37 UTC, jsonwan commented on src/backend/job-analysis/service-job-analysis/src/main/java/com/tencent/bk/job/analysis/dao/impl/AIChatHistoryDAOImpl.java
> +        val sql = query.getSQL(ParamType.INLINED);
SQL渲染阶段没有显式的异常抛出，到目前为止也没发现有渲染阶段的异常，可以放外面

2024-09-14 12:39 UTC, jsonwan commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/config/BkApiGatewayProperties.java
> +        private String appCode;
AI接口并非所有环境都有，这里是为某些环境跨环境调用AI接口提供一种覆盖机制。

2024-09-14 12:48 UTC, jsonwan commented on src/backend/commons/common-mysql/src/main/java/com/tencent/bk/job/common/mysql/dao/BaseDAOImpl.java
> +            sql = query.getSQL(ParamType.INLINED);
已修改

2024-09-14 12:53 UTC, jsonwan commented on src/backend/job-analysis/service-job-analysis/src/main/java/com/tencent/bk/job/analysis/api/web/impl/WebAIResourceImpl.java
> +        greetingChatHistory.setErrorCode("0");
已修改

2024-09-14 12:54 UTC, jsonwan commented on src/backend/job-analysis/service-job-analysis/src/main/java/com/tencent/bk/job/analysis/dao/impl/AIChatHistoryDAOImpl.java
> + * 仿照AnalysisTaskDAOImpl实现一个AIChatHistoryDAOImpl
给Copilot的提示性注释，已删除。

2024-09-14 12:57 UTC, jsonwan commented on src/backend/job-analysis/service-job-analysis/src/main/java/com/tencent/bk/job/analysis/service/ai/context/impl/FileTaskContextService.java
> +        assert (mode != null);
已删除

2024-09-14 12:57 UTC, jsonwan commented on src/backend/job-analysis/service-job-analysis/src/main/java/com/tencent/bk/job/analysis/service/ai/context/impl/FileTaskContextService.java
> +        assert (mode != null);
已删除

2024-09-14 12:57 UTC, jsonwan commented on src/backend/job-analysis/service-job-analysis/src/main/java/com/tencent/bk/job/analysis/service/ai/impl/AIChatHistoryServiceImpl.java
> +        int batchSize = 10000;
已修改

2024-09-14 13:06 UTC, jsonwan commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/sdk/BkApiClient.java
> +    public <T, R> R requestApiAndWrapResponse(OpenApiRequestInfo<T> requestInfo,
现有的requestApiAndWrapResponse方法比新增的方法多了一个BkApiContext<T, R>参数，并且现有方法的返回值与BkApiContext都与EsbResp类型强绑定，但是AI接口的响应格式并非EsbResp类型，仔细对比两个方法可以发现，很相似但不同，每隔2~3行就有差异（apiContext的赋值穿插其中），抽取公共代码的价值不大。

2024-09-14 13:06 UTC, jsonwan commented on src/backend/job-analysis/service-job-analysis/src/main/java/com/tencent/bk/job/analysis/dao/impl/AIChatHistoryDAOImpl.java
> +        Long existStartTime = dslContext.select(defaultTable.START_TIME)
更改实现方式后已删除。

2024-09-18 09:14 UTC, wangyu096 commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/config/BkApiGatewayProperties.java
> +        private String appCode;
ok

2024-09-18 09:20 UTC, wangyu096 approved these changes

2024-09-20 03:30 UTC, merged