feat: 执行引擎任务调度配额限制 #261
TencentBlueKing/bk-job pull request #3075
Opened 2024-06-20 09:55 UTC by wangyu096

2024-07-01 06:34 UTC, jsonwan commented on src/backend/commons/common-service/src/main/java/com/tencent/bk/job/common/service/quota/config/parser/AbstractResourceQuotaConfigParser.java
> +        parseGlobalLimit(resourceScopeQuotaLimit, capacity, globalLimitExpr);
建议与下一行的设置方式风格保持一致

2024-07-01 06:59 UTC, jsonwan commented on src/backend/job-analysis/boot-job-analysis/src/main/java/com/tencent/bk/job/analysis/JobAnalysisBootApplication.java
> +@EnableConfigurationProperties({FeatureToggleConfig.class, ResourceQuotaLimitProperties.class})
该注解建议放到FeatureToggleAutoConfiguration与ResourceQuotaAutoConfiguration上，不必散落到各个服务中。

2024-07-01 10:20 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/engine/listener/JobListener.java
> -                    break;
这里去除的原因是？

2024-07-01 12:14 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/engine/quota/limit/RunningJobResourceQuotaManager.java
> + * 正在执行作业配置限制管理
配置->配额

2024-07-01 12:35 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/impl/TaskExecuteServiceImpl.java
> +        // 记录到当前正在运行的任务存储中，用于配额限制
运行执行方案时也应当有该步骤，当前是缺失的，需要检查下

2024-07-01 12:37 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/impl/TaskExecuteServiceImpl.java
> +        // 记录到当前正在运行的任务存储中，用于配额限制
运行执行方案时也应当有该步骤，当前是缺失的，需要检查下

2024-07-01 12:40 UTC, jsonwan requested changes
几个问题需要处理

2024-07-02 01:34 UTC, wangyu096 commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/engine/listener/JobListener.java
> -                    break;
restart是指从头开始执行作业，目前这个操作是不支持的。这个功能从老版本 job 移植过来，未经过任何测试，这部分代码留着容易误导，并且需要维护工作量，不如直接删除，等后续有这个新的需求之后再重新设计

2024-07-02 01:46 UTC, wangyu096 commented on src/backend/commons/common-service/src/main/java/com/tencent/bk/job/common/service/quota/config/parser/AbstractResourceQuotaConfigParser.java
> +        parseGlobalLimit(resourceScopeQuotaLimit, capacity, globalLimitExpr);
fixed

2024-07-02 01:54 UTC, wangyu096 commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/engine/quota/limit/RunningJobResourceQuotaManager.java
> + * 正在执行作业配置限制管理
fixed

2024-07-02 03:10 UTC, wangyu096 commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/impl/TaskExecuteServiceImpl.java
> +        // 记录到当前正在运行的任务存储中，用于配额限制
fixed

2024-07-02 03:47 UTC, wangyu096 commented on src/backend/job-analysis/boot-job-analysis/src/main/java/com/tencent/bk/job/analysis/JobAnalysisBootApplication.java
> +@EnableConfigurationProperties({FeatureToggleConfig.class, ResourceQuotaLimitProperties.class})
fixed

2024-07-02 03:58 UTC, wangyu096 commented
已处理 review 问题

2024-07-02 04:00 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/engine/listener/JobListener.java
> -                    break;
OK

2024-07-02 04:13 UTC, jsonwan approved these changes

2024-07-02 06:34 UTC, merged