feat: Job 接入蓝鲸网关 #3150
TencentBlueKing/bk-job pull request #3165
Opened 2024-08-09 07:03 UTC by liuliaozhong

2024-08-20 09:40 UTC, wangyu096 requested changes

2024-08-20 09:40 UTC, wangyu096 commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/filter/esb/CheckEsbJwtGatewayFilterFactory.java
>              String token = RequestUtil.getHeaderValue(request, JobCommonHeaders.BK_GATEWAY_JWT);
这个 header 需要在蓝鲸网关注册插件来实现在请求中增加一个 header 。看了下，似乎这里并没有实现？

2024-08-20 09:40 UTC, wangyu096 commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/service/impl/EsbJwtPublicKeyServiceImpl.java
>      public EsbJwtPublicKeyServiceImpl(AppProperties appProperties,
目前同时接入了 esb和蓝鲸网关，这个类里边包含了其实是两个接入网关类型的代码，使用 ESBXX 命名不是太合适。建议把 ESB 、BkApiGateway 抽象为 OpenApiXXX这种，感觉更合理些。其他这里的几个类类似

2024-08-22 09:25 UTC, liuliaozhong commented on support-files/kubernetes/images/build.sh
> +        elif [[ "$MODULE" == "job-sync-api-gateway" ]]; then
已改

2024-08-22 09:26 UTC, liuliaozhong commented on docs/apidoc/bk-api-gateway/v3/resources.yaml
> +  /v2/jobv3/fast_execute_script:
已改

2024-08-22 09:28 UTC, liuliaozhong commented on docs/apidoc/bk-api-gateway/v3/resources.yaml
> +        allowApplyPermission: false
已改，用户态+应用态接口，公开允许申请权限

2024-08-22 11:13 UTC, liuliaozhong commented on support-files/kubernetes/images/build.sh
>  	    elif [[ "$MODULE" == "startup-controller" ]]; then
已改

2024-08-22 11:14 UTC, liuliaozhong commented on support-files/kubernetes/images/api-gateway/apigw-manager.Dockerfile
> +FROM python:3.7-slim-buster
是的，用蓝鲸网关构提供的，这个dockerFile没用到，已移除

2024-08-22 11:20 UTC, liuliaozhong commented on support-files/kubernetes/charts/bk-job/templates/job-migration/sync-apigateway-job.yaml
> +        - name: BK_NODEMAN_APP_CODE
已去掉

2024-08-22 11:32 UTC, liuliaozhong commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/service/impl/EsbJwtServiceImpl.java
> +                if ((!isVerified || StringUtils.isEmpty(appCode)) && !requestFromApiGw()) {
已修改

2024-08-22 11:34 UTC, liuliaozhong commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/service/impl/EsbJwtServiceImpl.java
> +                if (userProps == null && !requestFromApiGw()) {
已修改

2024-08-22 11:39 UTC, liuliaozhong commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/filter/esb/CheckEsbJwtGatewayFilterFactory.java
>              String token = RequestUtil.getHeaderValue(request, JobCommonHeaders.BK_GATEWAY_JWT);
有实现，在配置文件definition.yaml中plugin_configs指定的，也可以手动在蓝鲸网关管理页面上设置和维护

2024-08-22 11:42 UTC, liuliaozhong commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/config/BkGatewayConfig.java
> +    @Value("${job.bkGateway.requestFrom:apigw}")
键、值可以在蓝鲸网关注册插件中指定，可以在蓝鲸网关管理页面上维护，所以这里写成可配置是不是好些？

2024-08-22 12:47 UTC, liuliaozhong commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/service/impl/EsbJwtPublicKeyServiceImpl.java
>      public EsbJwtPublicKeyServiceImpl(AppProperties appProperties,
已修改

2024-08-22 12:50 UTC, liuliaozhong commented on support-files/kubernetes/charts/bk-job/values.yaml
> +  nodemanAppCode: "bk_nodeman"
已移除

2024-08-22 12:52 UTC, liuliaozhong commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/service/impl/EsbJwtServiceImpl.java
> +        if (bkGatewayConfig.isEnabled() && StringUtils.equals(bkGatewayConfig.getRequestFrom(), requestFrom)) {
已修改

2024-08-22 13:04 UTC, liuliaozhong commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/service/impl/EsbJwtServiceImpl.java
> +
已修改

2024-08-23 02:35 UTC, liuliaozhong commented on support-files/kubernetes/charts/bk-job/values.yaml
> +  enabled: false
已修改

2024-08-23 04:06 UTC, wangyu096 commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/config/BkGatewayConfig.java
> +    @Value("${job.bkGateway.requestFrom:apigw}")
这里固定的就好了，形成约定。灵活配置似乎也没有什么收益，还容易出错。 apigw 有点太通用，说不会会跟调用方自定义的 header 冲突。改成 bk-job-apigw

2024-08-23 05:48 UTC, liuliaozhong commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/config/BkGatewayConfig.java
> +    @Value("${job.bkGateway.requestFrom:apigw}")
好的，已改

2024-08-23 06:35 UTC, wangyu096 requested changes

2024-08-23 06:35 UTC, wangyu096 commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/config/BkGatewayConfig.java
> +    @Value("${job.bkApiGateway.requestFrom:apigw}")
这个跟插件对应，设置成固定值就行了。不需要支持配置

2024-08-23 06:37 UTC, wangyu096 commented on docs/apidoc/bk-api-gateway/v3/resources.yaml
> +  /v2/jobv3/fast_execute_script:
ok

2024-08-23 06:37 UTC, wangyu096 commented on docs/apidoc/bk-api-gateway/v3/resources.yaml
> +        allowApplyPermission: false
ok

2024-08-23 06:37 UTC, wangyu096 commented on support-files/kubernetes/charts/bk-job/templates/_helpers.tpl
> +{{ include "common.images.image" (dict "imageRoot" .Values.apiGatewayConfig.image "global" .Values.global) }}
ok

2024-08-23 06:37 UTC, wangyu096 commented on support-files/kubernetes/charts/bk-job/templates/configmap-common.yaml
> +        url: {{ .Values.apiGatewayConfig.apiUrl }}
ok

2024-08-23 06:37 UTC, wangyu096 commented on support-files/kubernetes/charts/bk-job/templates/job-gateway/configmap.yaml
> +      bkGateway:
ok

2024-08-23 06:37 UTC, wangyu096 commented on support-files/kubernetes/images/api-gateway/apigw-manager.Dockerfile
> +FROM python:3.7-slim-buster
ok

2024-08-23 06:37 UTC, wangyu096 commented on support-files/kubernetes/charts/bk-job/values.yaml
> +  nodemanAppCode: "bk_nodeman"
ok

2024-08-23 06:37 UTC, wangyu096 commented on support-files/kubernetes/charts/bk-job/values.yaml
> +  enabled: false
ok

2024-08-23 06:37 UTC, wangyu096 commented on support-files/kubernetes/charts/bk-job/templates/job-migration/sync-apigateway-job.yaml
> +        - name: BK_NODEMAN_APP_CODE
ok

2024-08-23 06:37 UTC, wangyu096 commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/service/impl/EsbJwtServiceImpl.java
> +
ok

2024-08-23 06:38 UTC, wangyu096 commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/service/impl/EsbJwtServiceImpl.java
> +                if ((!isVerified || StringUtils.isEmpty(appCode)) && !requestFromApiGw()) {
ok

2024-08-23 06:38 UTC, wangyu096 commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/filter/esb/CheckEsbJwtGatewayFilterFactory.java
>              String token = RequestUtil.getHeaderValue(request, JobCommonHeaders.BK_GATEWAY_JWT);
ok

2024-08-23 06:38 UTC, wangyu096 commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/service/impl/EsbJwtPublicKeyServiceImpl.java
>      public EsbJwtPublicKeyServiceImpl(AppProperties appProperties,
ok

2024-08-23 07:00 UTC, liuliaozhong commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/config/BkGatewayConfig.java
> +    @Value("${job.bkApiGateway.requestFrom:apigw}")
已改

2024-08-23 07:01 UTC, liuliaozhong commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/config/BkGatewayConfig.java
> +    @Value("${job.bkApiGateway.enabled:false}")
已改

2024-08-23 07:02 UTC, liuliaozhong commented on docs/apidoc/bk-api-gateway/v3/definition.yaml
>  grant_permissions:
已删除

2024-09-02 08:24 UTC, wangyu096 requested changes

2024-09-02 08:24 UTC, wangyu096 commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/service/impl/OpenApiJwtServiceImpl.java
> +            if (this.esbJwtPublicKey == null) {
这里是通过后台的方式获取 public key, 如果获取key 流程有问题，程序不会终止，而是继续运行，会带来风险。建议这里可以优化下，通过配置来控制是否failFast 。配置项：job.bkApiGateway.jwtPublicKey.get.failPolicy: abort(终止程序启动）/retry（后台重试，不影响程序启动） 。默认为 retry,与之前逻辑保持一致。

2024-09-02 10:14 UTC, liuliaozhong commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/service/impl/OpenApiJwtServiceImpl.java
> +            if (this.esbJwtPublicKey == null) {
已优化

2024-09-02 10:23 UTC, wangyu096 requested changes

2024-09-02 10:23 UTC, wangyu096 commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/service/impl/OpenApiJwtServiceImpl.java
> +            throw new AbortedException(ErrorCode.FAIL_TO_GET_JWB_PUBLIC_KEY);
AbortedException 指的的客户端断开连接错误。这里应该属于内部异常，直接抛出 InternalException.

2024-09-02 10:23 UTC, wangyu096 commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/service/impl/OpenApiJwtServiceImpl.java
> +        } else if ("abort".equalsIgnoreCase(bkApiGatewayConfig.getJwtPublicKeyFailPolicy())) {
需要判断其他情况，else 分支，抛出 InternalException("Illegal jwt public key get fail policy")

2024-09-02 10:35 UTC, liuliaozhong commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/service/impl/OpenApiJwtServiceImpl.java
> +            throw new AbortedException(ErrorCode.FAIL_TO_GET_JWB_PUBLIC_KEY);
已改

2024-09-02 10:35 UTC, liuliaozhong commented on src/backend/job-gateway/src/main/java/com/tencent/bk/job/gateway/service/impl/OpenApiJwtServiceImpl.java
> +        } else if ("abort".equalsIgnoreCase(bkApiGatewayConfig.getJwtPublicKeyFailPolicy())) {
已改

2024-09-03 03:47 UTC, wangyu096 approved these changes

2024-09-03 03:47 UTC, merged