perf: migrate迁移sql脚本支持自定义数据库账号 #3166
TencentBlueKing/bk-job pull request #3178
Opened 2024-08-22 08:57 UTC by liuliaozhong

2024-08-22 09:28 UTC, jsonwan commented
之前的做法是不太好的，建议将BK_JOB_MYSQL_ROOT_USERNAME与BK_JOB_MYSQL_ROOT_PASSWORD这两个变量通过secret挂载的方式传入，提高安全性。

2024-08-27 02:35 UTC, liuliaozhong commented
> 之前的做法是不太好的，建议将BK_JOB_MYSQL_ROOT_USERNAME与BK_JOB_MYSQL_ROOT_PASSWORD这两个变量通过secret挂载的方式传入，提高安全性。

ok

2024-09-03 06:50 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/templates/_helpers.tpl
> +{{- define "job.mariadb.adminUsername" -}}
migration使用的username和password建议与mariadb的配置项分开，放到job.migration.mysqlSchema下，变量的命名建议：
job.migration.mysql.adminUsername
job.migration.mysql.adminPassword
在实现逻辑上，需要保证向前的兼容性，如果用户单独配置了migration使用的用户名/密码，则优先使用，否则使用root+mariadb/externalMariaDB的root密码

2024-09-03 06:55 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/values.yaml
> -    rootPassword: "job"
rootPassword不可修改，它不仅用于migration，也用于部署内置mysql时的初始化，会传递给mariadb:11.0.10这个引用的chart，adminUsername与adminPassword建议挪到job.migration.mysqlSchema的配置里面去，默认值保持与这里root、rootPassword的值一致

2024-09-03 06:56 UTC, jsonwan requested changes
2个问题需要处理

2024-09-03 06:58 UTC, jsonwan commented
与values.yaml文件相同目录下的VALUES_LOG.md文件中需要同步添加相应配置项的说明

2024-09-04 12:21 UTC, liuliaozhong commented on support-files/kubernetes/charts/bk-job/templates/_helpers.tpl
> +{{- define "job.mariadb.adminUsername" -}}
已修改

2024-09-04 12:21 UTC, liuliaozhong commented on support-files/kubernetes/charts/bk-job/values.yaml
> -    rootPassword: "job"
已修改

2024-09-04 12:21 UTC, liuliaozhong commented
> 与values.yaml文件相同目录下的VALUES_LOG.md文件中需要同步添加相应配置项的说明

已添加

2024-09-05 06:35 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/VALUES_LOG.md
> +    mysql:
建议去除这一行，就放到mysqlSchema下面，免得让人误以为有3种migration动作

2024-09-05 06:35 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/templates/_helpers.tpl
> +Return the migrate mysql admin username
建议mysql统一改成mysqlSchema

2024-09-05 06:35 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/templates/_helpers.tpl
> +{{- define "job.migration.mysql.adminUsername" -}}
建议mysql统一改成mysqlSchema

2024-09-05 06:35 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/templates/_helpers.tpl
> +{{- printf "%s" .Values.job.migration.mysql.adminUsername | default "root" -}}
建议mysql统一改成mysqlSchema

2024-09-05 06:35 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/templates/_helpers.tpl
> +Return the migrate mysql admin password
建议mysql统一改成mysqlSchema

2024-09-05 06:36 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/templates/_helpers.tpl
> +{{- define "job.migration.mysql.adminPassword" -}}
建议mysql统一改成mysqlSchema

2024-09-05 06:36 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/templates/_helpers.tpl
> +{{- if .Values.job.migration.mysql.adminPassword -}}
建议mysql统一改成mysqlSchema

2024-09-05 06:36 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/templates/_helpers.tpl
> +    {{- printf "%s" .Values.job.migration.mysql.adminPassword -}}
建议mysql统一改成mysqlSchema

2024-09-05 06:36 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/templates/secret-migrationDB.yaml
> +  admin-username: {{ include "job.migration.mysql.adminUsername" . | b64enc | quote }}
建议mysql统一改成mysqlSchema

2024-09-05 06:37 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/values.yaml
> +    mysql:
建议去除这一行，就放到mysqlSchema下面，免得让人误以为有3种migration动作

2024-09-05 06:38 UTC, jsonwan reviewed
1处命名建议修改

2024-09-05 06:52 UTC, liuliaozhong commented on support-files/kubernetes/charts/bk-job/VALUES_LOG.md
> +    mysql:
已移除

2024-09-05 06:54 UTC, liuliaozhong commented on support-files/kubernetes/charts/bk-job/templates/_helpers.tpl
> +Return the migrate mysql admin username
已改

2024-09-05 06:54 UTC, liuliaozhong commented on support-files/kubernetes/charts/bk-job/templates/_helpers.tpl
> +{{- define "job.migration.mysql.adminUsername" -}}
已改

2024-09-05 06:54 UTC, liuliaozhong commented on support-files/kubernetes/charts/bk-job/templates/_helpers.tpl
> +{{- printf "%s" .Values.job.migration.mysql.adminUsername | default "root" -}}
已改

2024-09-05 06:55 UTC, liuliaozhong commented on support-files/kubernetes/charts/bk-job/templates/_helpers.tpl
> +Return the migrate mysql admin password
已改

2024-09-05 06:56 UTC, liuliaozhong commented on support-files/kubernetes/charts/bk-job/templates/_helpers.tpl
> +{{- if .Values.job.migration.mysql.adminPassword -}}
已改

2024-09-05 06:56 UTC, liuliaozhong commented on support-files/kubernetes/charts/bk-job/templates/_helpers.tpl
> +    {{- printf "%s" .Values.job.migration.mysql.adminPassword -}}
已改

2024-09-05 06:56 UTC, liuliaozhong commented on support-files/kubernetes/charts/bk-job/templates/secret-migrationDB.yaml
> +  admin-username: {{ include "job.migration.mysql.adminUsername" . | b64enc | quote }}
已改

2024-09-05 06:56 UTC, liuliaozhong commented on support-files/kubernetes/charts/bk-job/templates/secret-migrationDB.yaml
> +  admin-password: {{ include "job.migration.mysql.adminPassword" . | b64enc | quote }}
已改

2024-09-05 06:57 UTC, liuliaozhong commented on support-files/kubernetes/charts/bk-job/values.yaml
> +    mysql:
已改

2024-09-05 07:13 UTC, jsonwan approved these changes

2024-09-05 07:13 UTC, merged