perf: 作业执行结果回调日志级别优化 #3097
TencentBlueKing/bk-job pull request #3210
Opened 2024-09-13 08:49 UTC by liuliaozhong

2025-03-13 04:08 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/engine/listener/CallbackListener.java
> +                CommonMetricNames.TASK_CALLBACK_HTTP_STATUS,
建议给指标添加appId、appCode、cronTaskId三个标签，用于对异常回调进行溯源分析，实现可参考LogSamplerImpl

2025-03-13 04:10 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/engine/listener/CallbackListener.java
> +            log.info("Final callback {}, taskInstanceId: {}, statusCode: {}, result: {}",
换行格式建议调整下，一行装不下的参数建议新起一行，一行一个参数，改动到的其他地方也建议检查处理下

2025-03-13 04:11 UTC, jsonwan requested changes
2个小问题需要处理下。

2025-03-13 07:43 UTC, liuliaozhong commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/engine/listener/CallbackListener.java
> +                CommonMetricNames.TASK_CALLBACK_HTTP_STATUS,
cronTaskId是否改成taskInstanceId？定时任务没有回调

2025-03-13 11:11 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/engine/listener/CallbackListener.java
> +                CommonMetricNames.TASK_CALLBACK_HTTP_STATUS,
那就去掉cronTaskId，taskInstanceId不行，标签取值太多会导致监控那边维度爆炸。

2025-03-18 06:51 UTC, liuliaozhong commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/engine/listener/CallbackListener.java
> +            log.info("Final callback {}, taskInstanceId: {}, statusCode: {}, result: {}",
已处理

2025-03-18 06:52 UTC, liuliaozhong commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/engine/listener/CallbackListener.java
> +                CommonMetricNames.TASK_CALLBACK_HTTP_STATUS,
好的

2025-03-18 08:11 UTC, jsonwan approved these changes

2025-03-18 08:11 UTC, merged