feature: 执行类操作支持按业务拓扑节点申请权限与鉴权 #3213
TencentBlueKing/bk-job pull request #3249
Opened 2024-10-14 13:11 UTC by jsonwan

1.支持主机拓扑路径补全、鉴权；
2.支持动态拓扑节点路径构造、鉴权；
3.支持生成动态拓扑节点的无权限申请URL；
4.支持缓存主机拓扑路径，缓存参数可配置。

2024-10-15 02:19 UTC, wangyu096 approved these changes

2024-10-15 02:56 UTC, wangyu096 requested changes
拓扑鉴权性能问题需要处理

2024-10-16 03:57 UTC, jsonwan commented
> 拓扑鉴权性能问题需要处理

1. 业务集请求不会命中拓扑路径查询条件，总QPS<100；
2. 优先从CMDB查询拓扑路径信息保证实时性，查询失败后降低为从本地DB缓存查询；
3. Redis缓存保留，默认开启。

2024-10-17 03:43 UTC, wangyu096 approved these changes

2024-10-31 04:01 UTC, jsonwan commented
1.优化日志打印，支持统计关键环节耗时；
2.支持动态开关主机拓扑路径服务；
3.缓存逻辑优化，处理Redis读写异常场景；
4.使用全局线程池获取主机拓扑路径，防止线程爆炸影响整个系统；
5.修复初始化时序导致的部分接口调用指标丢失问题；
6.记录AuthHelper.isAllow方法调用结果统计数据。

2024-10-31 12:15 UTC, jsonwan commented
1.优化job-execute的Redis连接池参数；
2.更新chartValues配置与变更记录。

2024-11-04 00:46 UTC, wangyu096 requested changes

2024-11-04 00:46 UTC, wangyu096 commented on support-files/kubernetes/charts/bk-job/templates/job-execute/configmap.yaml
> +          {{- toYaml .Values.executeConfig.iam | nindent 10 }}
job-assemble 轻量化部署模式下没有支持按照拓扑鉴权

2024-11-04 04:12 UTC, jsonwan commented on support-files/kubernetes/charts/bk-job/templates/job-execute/configmap.yaml
> +          {{- toYaml .Values.executeConfig.iam | nindent 10 }}
已添加。

2024-11-05 02:39 UTC, wangyu096 approved these changes

2024-11-05 02:39 UTC, merged