fix: 修复分库分表引入的问题 #3332
TencentBlueKing/bk-job pull request #3335
Opened 2024-12-17 02:12 UTC by wangyu096

1. 修复 RepeatableReadWriteServletRequestResponseFilter 报错问题，仅对ContentType=application/json 的请求生效
2. 修复归档开关 job.backup.archive.execute.enabled=false的情况下，job-backup 微服务无法启动的问题
3. 修复部分 DAO 层方法没有使用动态构造 task_instance_id 条件的问题（StepInstanceDaoImpl.java)
4. 修复部分场景依赖 id 作为逻辑熟悉的问题（比如按照 step_instance_id 的大小判断在执行方案中的顺序，正确的应该是使用 stepOrder 字段)

2024-12-17 08:34 UTC, jsonwan commented on src/backend/commons/common-web/src/main/java/com/tencent/bk/job/common/web/filter/RepeatableReadWriteServletRequestResponseFilter.java
> +        return contentType.startsWith("application/json");
Content-Type 头字段的值是大小写不敏感的，建议增加toLowerCase()后再判断。

2024-12-17 08:48 UTC, jsonwan requested changes
1个问题需处理

2024-12-17 08:49 UTC, wangyu096 commented on src/backend/commons/common-web/src/main/java/com/tencent/bk/job/common/web/filter/RepeatableReadWriteServletRequestResponseFilter.java
> +        return contentType.startsWith("application/json");
fixed

2024-12-18 01:43 UTC, jsonwan approved these changes

2024-12-18 01:44 UTC, merged