perf: 优化local文件不存在时的报错信息 issue #2986
TencentBlueKing/bk-job pull request #3338
Opened 2024-12-17 09:10 UTC by wuyzh39

2024-12-19 01:50 UTC, jsonwan commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/model/EsbResp.java
> +        return new EsbResp<>(errorCode, message, null);
建议简化为直接调用3个参数的buildCommonFailResp方法。

2024-12-19 01:59 UTC, jsonwan commented on src/backend/commons/artifactory-sdk/src/main/java/com/tencent/bk/job/common/artifactory/sdk/ArtifactoryClient.java
> +
异常处理逻辑建议抽取成单独的方法，降低代码复杂度。

2024-12-19 01:59 UTC, jsonwan commented on src/backend/commons/artifactory-sdk/src/main/java/com/tencent/bk/job/common/artifactory/sdk/ArtifactoryClient.java
> +                ArtifactoryResp<Object> artifactoryResp = JsonUtils.fromJson(httpStatusExceptionRespStr,
httpStatusExceptionRespStr可能为null，这里可能报空指针异常，建议提前判断。

2024-12-19 02:10 UTC, jsonwan commented on src/backend/commons/artifactory-sdk/src/main/java/com/tencent/bk/job/common/artifactory/sdk/ArtifactoryClient.java
>              status = "error";
对于文件不存在的请求，status可以区分一下，建议用一个单独的status=“clientError.nodeNotFound”，指标的Tag与Value可以抽取到一个单独的MetricsConstants类中，可参考其他已实现的MetricsConstants类。

2024-12-19 02:13 UTC, jsonwan commented on src/backend/commons/artifactory-sdk/src/main/java/com/tencent/bk/job/common/artifactory/sdk/ArtifactoryClient.java
> +
外层try块中的嵌套try-catch可以省略，异常统一在外层处理。

2024-12-19 02:19 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/ArtifactoryLocalFileService.java
> +                    ErrorCode.LOCAL_FILE_NOT_EXIST_IN_BACKEND,
这个错误码的提示信息不够清晰，建议修改为：
本地文件{0}在后台不存在，可能已过期（{1}天）被自动清理，如有必要请重新上传后重试，如果需要持久化存储，请从业务的服务器分发

2024-12-19 02:19 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/ArtifactoryLocalFileService.java
> +            if (e.getErrorCode() == ErrorCode.CAN_NOT_FIND_NODE_IN_ARTIFACTORY) {
异常处理逻辑建议抽象为单独的方法。

2024-12-19 02:20 UTC, jsonwan requested changes
几个优化点需要优化下。

2024-12-20 01:52 UTC, wuyzh39 commented on src/backend/commons/esb-sdk/src/main/java/com/tencent/bk/job/common/esb/model/EsbResp.java
> +        return new EsbResp<>(errorCode, message, null);
fixed

2024-12-20 01:54 UTC, wuyzh39 commented on src/backend/commons/artifactory-sdk/src/main/java/com/tencent/bk/job/common/artifactory/sdk/ArtifactoryClient.java
>              status = "error";
clientError.nodeNotFound 放在了 com.tencent.bk.job.common.metrics.CommonMetricValues 中

2024-12-20 01:54 UTC, wuyzh39 commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/ArtifactoryLocalFileService.java
> +                    ErrorCode.LOCAL_FILE_NOT_EXIST_IN_BACKEND,
fixed

2024-12-20 01:54 UTC, wuyzh39 commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/ArtifactoryLocalFileService.java
> +            if (e.getErrorCode() == ErrorCode.CAN_NOT_FIND_NODE_IN_ARTIFACTORY) {
fixed

2024-12-20 01:58 UTC, wuyzh39 commented on src/backend/commons/artifactory-sdk/src/main/java/com/tencent/bk/job/common/artifactory/sdk/ArtifactoryClient.java
> +
嵌套try去掉了，处理HttpStatusException并检查错误码是否是RESULT_CODE_NODE_NOT_FOUND的逻辑没有抽出来，因为要在当中处理status，在finally中才会使用这个status（总不能传个引用到方法里面吧）

2024-12-20 06:33 UTC, jsonwan commented on src/backend/commons/artifactory-sdk/src/main/java/com/tencent/bk/job/common/artifactory/sdk/ArtifactoryClient.java
>              status = "error";
1. common模块下面的代码是所有上层模块共用的底层公共代码，制品库接口特有的指标标签数据建议就放在artifactory-sdk模块的constants包中；
2. 这个方法中的status 所有取值都应当抽取为常量，便于将来使用指标数据时能快速定位到所有可能的标签值，而非只针对一个取值；
3. 指标标签的Key建议也抽取到常量类中。

2024-12-20 06:36 UTC, jsonwan commented on src/backend/commons/artifactory-sdk/src/main/java/com/tencent/bk/job/common/artifactory/sdk/ArtifactoryClient.java
> +
是否可以把status作为抽取方法的返回值呢？

2024-12-20 06:53 UTC, jsonwan commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/ArtifactoryLocalFileService.java
>          log.debug("nodeDTpwO={}", nodeDTO);
日志中的拼写错误看到了就帮忙顺手改一下，thanks

2024-12-20 06:54 UTC, jsonwan requested changes
3个问题需要再处理下。

2024-12-20 07:58 UTC, wuyzh39 commented on src/backend/commons/artifactory-sdk/src/main/java/com/tencent/bk/job/common/artifactory/sdk/ArtifactoryClient.java
>              status = "error";
fixed

2024-12-20 07:59 UTC, wuyzh39 commented on src/backend/job-execute/service-job-execute/src/main/java/com/tencent/bk/job/execute/service/ArtifactoryLocalFileService.java
>          log.debug("nodeDTpwO={}", nodeDTO);
fixed

2024-12-20 07:59 UTC, wuyzh39 commented on src/backend/commons/artifactory-sdk/src/main/java/com/tencent/bk/job/common/artifactory/sdk/ArtifactoryClient.java
> +                ArtifactoryResp<Object> artifactoryResp = JsonUtils.fromJson(httpStatusExceptionRespStr,
fixed

2024-12-20 07:59 UTC, wuyzh39 commented on src/backend/commons/artifactory-sdk/src/main/java/com/tencent/bk/job/common/artifactory/sdk/ArtifactoryClient.java
> +
fixed

2024-12-20 09:22 UTC, jsonwan approved these changes

2024-12-20 09:24 UTC, merged